### ISSUE TITLE
IE10 vertical scrollbar

### ISSUE THREAD

**Issue by Dennis1993** [lokesh/lightbox2#105]
Hello guys,

if I use the firefox, the picture is ok.
If I open the same with Internet Explorer 10 I have every time a vertical scrollbar.
So I can scroll 17px or so to the right.

I have tested it with the current version 2.6
Browser: Internet Explorer 10
OS: Windows 8

Can anyone reproduce it?

Sorry for my bad english :)

**Comment by lokesh** [comment]
Closing out old, inactive issues.

I did this test the latest version of Lightbox in IE10 and was not able to reproduce any scrollbar issues.
