### ISSUE TITLE
Add translation support for lightbox

### ISSUE THREAD

**Issue by ekaukis** [lokesh/lightbox2#113]
This is my suggestion how to add language support for lightbox2, in my case I did these steps described below.
1. Make lightbox object available from code by adding lightbox object to window.

```
window.lightbox = new Lightbox options 
```
1. Lightbox options could look like this:

```
class LightboxOptions
  constructor: () ->
    @fadeDuration         = 500
    @fitImagesInViewport  = true 
    @resizeDuration       = 700
    @showImageNumberLabel = true
    @wrapAround           = false
    @translations         = {image: "Image", of: "of"} 

  # Change to localize to non-english language
  albumLabel: (curImageNum, albumSize) ->
    "#{@translations["image"]} #{curImageNum} #{@translations["of"]} #{albumSize}"
```
1. Add method setTranslations to Lightbox class

```
  setTranslations: (translations) ->
    @options.translations = translations
```
1. In code, forexample ruby, you can use it like

```
<script type="text/javascript">  
lightbox.setTranslations({image: "<%= t("public.common.lbox_image") %>", of: "<%= t("public.common.lbox_of") %>"} )
</script>
```

Hope this will help someone!

**Comment by matriphe** [comment]
+1 for localization!

**Comment by webdesign4wien** [comment]
+1 for localization!

**Comment by elcodedocle** [comment]
+1!

**Comment by RyanZim** [comment]
@lokesh This is solved by the albumLabel option. Shouldn't this be closed?

**Comment by lokesh** [comment]
Yes, this should have been closed. oops

If something more than the existing `albumLabel` option is required than I can reopen this issue.
