### ISSUE TITLE
Zoom capability

### ISSUE THREAD

**Issue by reetzam12** [lokesh/lightbox2#126]
After clicking on the thumbnail and bringing up your full-size image, is it possible to zoom in on certain parts of the image without having to zoom in the entire page? I'm trying to create an online portfolio of newspaper clippings where the full newspaper page comes up after clicking the thumbnail and would like viewers to be able to zoom in on different articles so they can actually read the content.

**Comment by FrEaKmAn** [comment]
I disagree. Having this feature on the mobile phones is sometimes a must.
