### ISSUE TITLE
Images too small in iphone landscape view

### ISSUE THREAD

**Issue by supergia** [lokesh/lightbox2#129]
I'm using Lightbox2 because my older version of Lightbox was conflicting with other jQuery scripts. I am now using Lightbox2 and everything is great except on the iphone 4 iOS 6 the landscape view of my Lightbox2 images are too small. In the portrait view they are fine. How can I fix this? Please see images. 
![131122-0001](https://f.cloud.github.com/assets/6012486/1603141/8239f2f6-53a4-11e3-9923-18bcfc081d02.jpg)
![131122-0002](https://f.cloud.github.com/assets/6012486/1603143/863925de-53a4-11e3-9f6f-c191715b357b.jpg)

**Comment by lokesh** [comment]
Closing out old, inactive issues.

I am investigating improvements for mobile layout and interaction. Nothing set yet.
