### ISSUE TITLE
alt text for images and ARIA techniques

### ISSUE THREAD

**Issue by jonathan-pund** [lokesh/lightbox2#138]
I'm working for a company that needs to be Section 508 compliant. The current lightbox does not allow a way to add or generate an "alt" element in the image that is shown in the lightbox. Nor does the lightbox add any ARIA roles or labels which would tell a user who is accessing the image using a screen reader that the screen had changed and that an image had popped up. 

Please let me know if these features are already implemented, so I may use them. If not, could you please implement them. For reference, I am trying to open the image using linked text in an unordered list, not an img element.

**Comment by tomek69** [comment]
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" class="lb-image" - missing alternative text alt="".

<a href="" class="lb-prev" </a - no text
<a href="" class="lb-next" </a - no text

Screen reader problems.

**Comment by lokesh** [comment]
Closing out old issues.

I've taken note of the feedback regarding alt text and ARIA techniques. I'm working on a brand new version of the script, v3.0, and it will address accessibility issues from the start versus the current version which has mostly ignored them.

Some of the accessibility issues I'm reviewing:
- Review alt attributes.
- Review ARIA roles.
- Review constrast ratios.
- Review tabbing.
- Review click/touch target size.
