### ISSUE TITLE
support for downloading image

### ISSUE THREAD

**Issue by kalvish21** [lokesh/lightbox2#140]
The image loads and everything is fine. But my users would like to be able to save the image after it loads (some other scripts allow right clicking, dragging the image, etc.). Is there anyway to add this feature to this?

Until then can't use it :(.

**Comment by pingyangtiaer** [comment]
@ margox
I downloaded https://github.com/Margox/lightbox2 and didn't find the download working, actually I can not find the download arrow show up when I hovering the mouse there. Are you sure it is working?
Thanks.

**Comment by clomaka** [comment]
Worked for me when I grabbed it a year or so ago.

**Comment by pingyangtiaer** [comment]
Not working for me yet. I even didn't find the next arrow. Could you please send me a working version?

**Comment by pingyangtiaer** [comment]
Is there a way to add a "download" text in the middle of the title with hyper link for download?

**Comment by clomaka** [comment]
http://www.megafileupload.com/2lLA/lightbox2.zip

**Comment by margox** [comment]
aha，yesterday I restyled this plugin,(in fact only modified the css file),and the image is no longer coverd by the prev/next buttons.so you can save the image just click the right mouse button as a normal web image,but I am  not beside  my computer now,because it's morning in China, I will  update this at about 10 am today(^_^)

**Comment by margox** [comment]
@pingyangtiaer 

see the snapshot below,do you like this style?

![image](https://cloud.githubusercontent.com/assets/7866354/7645263/e04cd87a-fae4-11e4-934f-f5df7258582f.png)

here is the link: [http://lazypress.net/lightbox2.zip](http://lazypress.net/lightbox2.zip)

**Comment by pingyangtiaer** [comment]
@margox 
Thanks for the sharing, However, I still did not see the download button yet.
I found out there was a pull to the github from you one year ago, I will try from there to seek luck.

**Comment by tonijn** [comment]
To enable the browser's native "save image as" functionality, please add to following css. No js needed:

```css
.lb-nav {
   pointer-events: none;
}

.lb-prev, .lb-next {
   pointer-events: auto;
}
```

**Comment by itsites** [comment]
Work for me:
`.lb-nav a.lb-prev, .lb-nav a.lb-next { width: 20% !important; }
.lb-nav { pointer-events: none; }
.lb-prev, .lb-next { pointer-events: auto; }`

**Comment by lokesh** [comment]
I've added the ability to use the browser's native right-click to save the image in a commit today:
https://github.com/lokesh/lightbox2/commit/363c3cb8af8fae1b6f95d6679df976022290f878

It'll be in the next release v2.9.0 coming out at the end of the weekend.
