### ISSUE TITLE
Full size of image

### ISSUE THREAD

**Issue by thinhnd** [lokesh/lightbox2#161]
please help me to show full size of image
ex: i have an albumn with 5 pictures 1366x768px
and i want it full size when display through light box.
with this code in this version, it usally has 1132x649px in my desktop
My desktop has screen resolution is 1440x900 px

**Comment by lokesh** [comment]
Closing out old issues.

There was a bug in earlier versions of Lightbox that affected the width of images after the first. This has been resolved.
