### ISSUE TITLE
Add Video to lightbox

### ISSUE THREAD

**Issue by bedrijvenabcNMCT** [lokesh/lightbox2#162]
Hello,

Is it possible to add video content to lightbox?
Then you can play a video with overlay and you can see the video's between the pictures? 
I think this would be a huge advantage for lightbox. 

Best regards,
Kris Thienpont

**Comment by Stephen304** [comment]
Is this ever going to happen?

**Comment by sonizef** [comment]
+1 !

**Comment by Hedde** [comment]
+1

**Comment by MarcGodard** [comment]
+1

**Comment by danielgwilson** [comment]
+1

**Comment by philipstratford** [comment]
+1

**Comment by MarcGodard** [comment]
Is this project still active? If not, maybe I can fork it and add this functionality.

**Comment by KaduAmaral** [comment]
@MarcGodard you can do this with active too.

**Comment by MarcGodard** [comment]
@KaduAmaral I know that. But if they are not maintaining it, why would they accept my pull request? Thats why I asked...

**Comment by KaduAmaral** [comment]
@MarcGodard, I think it's maintained, have a some issues closed at few days ago.

**Comment by mehdiraized** [comment]
+1

**Comment by Dan233** [comment]
I m begging for you to add this feature. Please

**Comment by lokesh** [comment]
You're not going to be happy to hear this but there is no video support planned.

This is a common request so I've updated to the readme's roadmap to note this.
https://github.com/lokesh/lightbox2#roadmap
## Roadmap

### Actively being worked on

- **Maintenance.** Get open Issues and PRs number down.

### Not on the roadmap

- **HTML or video content.** The goal of the script from the start has been to provide a better image viewing experience and I am planning on staying focused on that vision. Don't worry though there are plenty of alternative scripts a google away for those who need HTML or video content support.

### v3.0 - In Brainstorming Phase
