### ISSUE TITLE
Center lightbox vertically

### ISSUE THREAD

**Issue by paexthetiker** [lokesh/lightbox2#172]
Hi,

as far as i can get from the code the lightbox is currently positioned like this:

top = $window.scrollTop() + $window.height() / 10;

so at a certain position from the top of the current position.
Is there a way to display the lightbox centered in the window. And also center it again on image change (otherwise if the new image has a different height it won't be centered anymore).

I tried working it out but did not get to change it.
Would appreciate any help!
Best,
Pascal

**Comment by Soullighter** [comment]
@gTempesta Thank you man. It works

**Comment by PortaMx** [comment]
works perfect .. as small note .. the ccs above must be add to the class .**lightbox{**

**Comment by jonathansigg** [comment]
```
#lightboxOverlay { position: fixed !important; top: 0; left: 0; height: 100% !important; width: 100% !important; }
#lightbox { position: fixed !important; top: 50% !important; transform: translateY(-50%); }
```

**Comment by alexrocco** [comment]
@jonathansigg 

Works perfect! Thanks.

**Comment by StudioZut** [comment]
@jonathansigg that is exactly what I was looking for, thanks!

**Comment by d2a-raudenaerde** [comment]
> ```
> #lightboxOverlay { position: fixed !important; top: 0; left: 0; height: 100% !important; width: 100% !important; }
> #lightbox { position: fixed !important; top: 50% !important; transform: translateY(-50%); }
> ```

This makes my image blurry.

**Comment by keslo** [comment]
> #lightboxOverlay { position: fixed !important; top: 0; left: 0; height: 100% !important; width: 100% !important; }
> #lightbox { position: fixed !important; top: 50% !important; transform: translateY(-50%); }

This is good solution for centering image.

**Comment by versedi** [comment]
2019 way of doing it - use flex.

```
.lightbox {
   align-content: center;
   align-items: center;
   height :100%;
   display: flex;
   flex-direction: column;
   position: fixed !important;
   top: 0 !important;
}

.lb-outerContainer {
    margin: auto;
}

.lb-image {
   margin: auto;
}

```

**Comment by Scott-Haugaard** [comment]
@jonathansigg

Perfect solution. Even though it was years ago, when searching StackOverflow the question hadn't been answered, so I linked yours with the code. Moderators changed the format for readability:

`#lightboxOverlay {
    position: fixed !important;
    top: 0;
    left: 0;
    height: 100% !important;
    width: 100% !important;
}

#lightbox {
    position: fixed !important;
    top: 50% !important;
    transform: translateY(-50%);
}`
