### ISSUE TITLE
preload images

### ISSUE THREAD

**Issue by radzhome** [lokesh/lightbox2#186]
When images are in the same group, the previous and next image are preloaded. This is costly for images generated by the server on request. Any way to disable this or add config for this to disable it?

**Comment by GeorgeTodea** [comment]
Hello, I need to disable the preloading images. Can you tell me again which line is to be removed from showImage() method? Thank you.

**Comment by rageforst** [comment]
Same here, on IOS browsers like safari and chrome, if you use a lot of high resolution images in the same group the page doesn't load… when I reduce the number of images it works, wich line do we need to remove in the shoyImage() method?

**Comment by lokesh** [comment]
My original comment had a markdown syntax issue which made it unreadable. Sorry!

Here is what I was trying to say for how to disable preloading:

> The change is simple though. Remove the following line in the showImage() method:
> `this.preloadNeighboringImages();`
