### ISSUE TITLE
Lightbox too small for subsequent larger images.

### ISSUE THREAD

**Issue by theandyyates** [lokesh/lightbox2#191]
After fixing the lightbox.css file with 

.lb-lightboxOuterContainer {
background-color: white;
  *zoom: 1;
  width: auto;
  height: auto;
  margin: 0 auto;
...............
}

I found that upon viewing an image in lightbox, the correct image size was rendered, unless a previous image had been viewed that was smaller that the current image, in which case the previous image width was maintained, and the new image aspect ratio was forced into the previous box size, distorting it.

I'm not too familiar with jQuery, but figured if I could reload the images on closing the lightbox, this would sort the problem:

from 115 of lightbox.js:

      this.$lightbox.on('click', function() {  // removed .find('.lb-loader, .lb-close')
        _this.end();
        location.reload();  // added to refresh page.
        return false;
      });
    };

The lightbox can now be closed by clicking or tapping anywhere around the image as well as on the 'X', and the page will be refreshed allowing jQuery to recalculate the image dimensions when next required. It would appear to fix the image size issue

This perhaps isn't ideal, as it forces a refresh every time a lightbox is closed.

Is there a better way?

**Comment by lokesh** [comment]
Closing out old issues.

There was a bug in earlier versions of Lightbox that affected the width of images after the first. This has been resolved.
