### ISSUE TITLE
Lightbox i div

### ISSUE THREAD

**Issue by B2zytek** [lokesh/lightbox2#198]
Hi everyone
I have a page built on three div's / div id = "framecontentLeft" / div id = "framecontentRight" / div id = "Maincontent" - div class = "innertube" id = "Layer2". / Sub-pages loading into / div class = "innertube" id = "Layer2" / using jquery-1.10.1.min by this code:
a href="#" onclick="$('#Layer2').load('english/about-name.htm'); return event.returnValue=false".
Same sub-page load ok, but called them LyteBox v3.22v in general does not open. Testing alone is not loaded page(div class = "innertube" id = "Layer2") LyteBox works ok
I note that I do not care for the latest version LyteBox.
How do you solve a problem loading LyteBox to div dynamically as the page is read?

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
