### ISSUE TITLE
Lightbox 2 navigation on ipad

### ISSUE THREAD

**Issue by patsan22** [lokesh/lightbox2#199]
I understand that the new version 2.7.0 has a setting to show navigation at all times on all touch devices. My question is, will this keep them on at all times only on the ipad and iphone?  I wouldn't want them to show at all times on a desktop or laptop etc.

2nd question: is there a way to move the nav. arrows outside of the picture frame?

**Comment by lokesh** [comment]
Old issue, but chiming in for any existing readers who might run across this.

Question 1:
```alwaysShowNavOnTouchDevices``` option will keep the navigation visible on any device with touch support which include not only phones and tablets, but now some laptops.

I'm working on a a full rewrite of Lightbox that adds better mobile and touch support with improved layouts and gestures. No date yet on this.

Question 2:
You can edit with the navigation css (.lb-next, .lb-prev) to move the arrows off the image. You'll need to use absolute positioning for these items and make sure the clickable area for navigating still overlaps the image.
