### ISSUE TITLE
add Copyright like title

### ISSUE THREAD

**Issue by cryadm** [lokesh/lightbox2#200]
Hi, i use Images from foreign owners and have to include the copyright , each time, the image is displayed. Copyright and title in one row does not look nice.
What about a new line in lb-data?
If i include it on my own, it will be overwritten by next Update from your side.

kind regards Charly

**Comment by lokesh** [comment]
Closing out old, inactive issues. 

There wasn't enough demand for this specific feature to bring it into the script.
