### ISSUE TITLE
Images disappear when adding lightbox

### ISSUE THREAD

**Issue by vivianliu94** [lokesh/lightbox2#204]
Using a "ultraboard" theme for my tumblr, vivianliu.tumblr.com. Trying to add a slideshow lightbox (b/w individual posts) rather than disconnected permalinks when clicking on each of the background photos. I also used the original lightbox instead of the newer version, mostly because I don't know how else to edit the CSS! Any help would be appreciated.

When I add this right before </head>, all the background images disappear.
<script type="text/javascript" src="http://static.tumblr.com/ge5u7cy/Xzmn3ujbr/prototype.js"></script>
<script type="text/javascript" src="http://static.tumblr.com/ge5u7cy/ZZnn3ujcq/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="http://static.tumblr.com/ge5u7cy/ndKn3ujcg/effects.js"></script>
<script type="text/javascript" src="http://static.tumblr.com/ge5u7cy/nOgn3ujc5/builder.js"></script>
<script type="text/javascript" src="http://static.tumblr.com/ge5u7cy/eYYn3ujb7/lightbox.js"></script>

I also tried to change the CSS for photo to include this after {LinkOpenTag}. But it didn't seem to do anything. 
<a href="{PhotoURL-HighRes}" rel="lightbox[image]" title="{PhotoAlt}">

This was the original CSS for {block:Photo}, without that edit: 

{block:Photo}
                        <div class="post photo">
                            {block:IndexPage}<img src="{PhotoURL-500}" alt="{PhotoAlt}"/>{/block:IndexPage}

                            {block:PermalinkPage}
                                {LinkOpenTag}
                                    <img class="image" src="{PhotoURL-HighRes}"/>
                                {LinkCloseTag}
                            {block:PermalinkPage}

                            {block:Caption}
                                <div class="caption">{Caption}</div>
                            {/block:Caption}
                        </div>
                    {/block:Photo}
                
                    {block:Photoset}
                        <div class="post photoset">
                            {Photoset-500}

                            {block:Caption}
                                <div class="caption">{Caption}</div>
                            {/block:Caption}
                        </div>
                    {/block:Photoset}

**Comment by lokesh** [comment]
Closing out old, inactive issues. If there is still an issue with Lightbox that you are seeing, please note and I will reopen and investigate. Thanks.
