### ISSUE TITLE
Wrong number of images in description

### ISSUE THREAD

**Issue by awilson3rd** [lokesh/lightbox2#212]
Hello, 

I know there was a previous case for this but I am using the latest version and the problem still happens for me. 

I have 5 images with the same data lightbox so they can be used in a gallery. I have 4 images but when the first image loads it starts with 'image 5 of 8' when I click through the images it comes back to the first one which is still seen as 'image 5 of 8'

Any ideas?

Thanks 

Andrew

**Comment by lokesh** [comment]
Old issue, but this might still be happening. If anyone is able to reproduce this issue consistently can you post a link or the relevant code below. Once you do that I will reopen this issue. Thanks.
