### ISSUE TITLE
URL to image / share

### ISSUE THREAD

**Issue by techtonik** [lokesh/lightbox2#214]
Lightbox doesn't seem to have an ability to share image by URL. It is a major drawback.
1. Direct link to image URL to paste to other web sites
2. Link to image to share with friends, so that it immediately opens right

**Comment by squareZ** [comment]
Yes, please realize this! +1

**Comment by lokesh** [comment]
Closing out old issues.

This feature is in the works for the next major release, v3.0. Thanks for the feedback.
