### ISSUE TITLE
Android Browser's unpleasent touch hover effect + Fix

### ISSUE THREAD

**Issue by arvindsa** [lokesh/lightbox2#215]
By Default, Android browser gives a blue/orange highlight for links touched (not not released) therefore giving a blue/orange tinge flicker on the image when the next or previous button is pressed. This is decive specific. and I find adding the following code eliminates it. Screenshot is attached.

.lb-nav a.lb-prev,.lb-nav a.lb-next{
	-webkit-tap-highlight-color: rgba(255, 255, 255, 0) !important; 
    -webkit-focus-ring-color: rgba(255, 255, 255, 0) !important; 
    outline: none !important;
	
![screenshot_2014-04-24-12-08-54](https://cloud.githubusercontent.com/assets/1448781/2786663/5b81793c-cb7b-11e3-9247-1fd977c3cc40.png)
}

**Comment by lokesh** [comment]
Closing out old, inactive issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.

I was not able to recreate this issue in the Android emulator. I just ordered an Android phone for testing. I hope to test again when it arrives in a couple of weeks.
