### ISSUE TITLE
Add image download link on lightbox.

### ISSUE THREAD

**Issue by thejpgarcia** [lokesh/lightbox2#216]
Right clicking the image just shows the options for the web app not the image. Can it be possible that right clicking will show up the options for the image or add a download feature on the lightbox.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
