### ISSUE TITLE
Lightbox overlay covers thumbnails

### ISSUE THREAD

**Issue by tanusgreystar** [lokesh/lightbox2#218]
Is there a way to configure lightbox to stay in a div while having a separate div for the thumbnails so that the overlay doesn't  cover the thumbs?

**Comment by lokesh** [comment]
Old issue, but quickly chiming in.

There is no way to use the built-in options with lightbox2 to get the results you are looking over. To get what you want, you would need to collect the location and size of the thumbnails prior to making the overlay visible and adjust the size and position of it accordingly.
