### ISSUE TITLE
LIGHTBOX - data-title doesn't work

### ISSUE THREAD

**Issue by JimmyGlee** [lokesh/lightbox2#219]
Hello, on my website the data-title doesn't work in my "CONSTRUCTION" page images, I don't understand why. When I add <script src="js/jquery-1.11.0.min.js"></script>, it adds something undermy footer with the nav icons, I don't understand how to manage this issue.

Can someone help me, that would be great.

Thank you very much in advance

**Comment by lokesh** [comment]
Closing out old, inactive issues. 

Let me know if there are any new or existing Lightbox issues and I can reopen and investigate. Thanks.
