### ISSUE TITLE
image does not popup but appears way at the bottom

### ISSUE THREAD

**Issue by jpdomein** [lokesh/lightbox2#220]
Hi, I have rebuild and redesigned a website (www.bcgemert.nl) removed all unneccessary scripts and added the lightbox. When the site is run locally, the popup of fotos works like a charm, once the site is uploaded the fotos do not popup but appear somewhere at the bottom of the browser. This happens in all browsers tested (opera, Firefox, IE).

What could be the cause of that?

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
