### ISSUE TITLE
open image by function in js

### ISSUE THREAD

**Issue by fgrs** [lokesh/lightbox2#223]
I have a set of images hooked up to the lightbox is there a way to open first image by function? is there actually any documentation available??

**Comment by rob-gordon** [comment]
+1

**Comment by lokesh** [comment]
Closing out old issues.

I'm in early stages of the next major iteration of the script, v3.0. I've taken note of the feedback and will be opening up the API to allow programatic opening/closing of component.

If you still need help with anything, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
