### ISSUE TITLE
Show filename

### ISSUE THREAD

**Issue by mectiv** [lokesh/lightbox2#226]
Hello everybody,

I need to Show the filename of the current image next to the title.
Tried to use following line without success:

this.$lightbox.find(".filename").html(this.album[this.currentImageIndex].link)

Thank you for any help.

Greetz
Christian

**Comment by lokesh** [comment]
Closing out old, inactive issues.

If there are still issues or things you are trying to achieve with Lightbox, please note and I will reopen and investigate. Thanks.
