### ISSUE TITLE
Overlay not covering viewport on iPad

### ISSUE THREAD

**Issue by sortitout** [lokesh/lightbox2#227]
Hi,

Anyone know how to resolve an issue with the overlay not covering the complete viewport on the iPad?  It covers just about 2/3 of the display in both landscape and portrait orientation.  At the sometime, the lightbox is left of center - likely related.

Thanks!

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
