### ISSUE TITLE
Overlay does not cover 100% of the document width

### ISSUE THREAD

**Issue by ghost** [lokesh/lightbox2#228]
i have a wide page (with h-scrollbar visible)
When i trigger the lightbox, the overlay doesn't cover the whole screen (obvious on iPhone)

changing $(window) to $(document) fixes the problem

```
Lightbox.prototype.sizeOverlay = function() {
  this.$overlay
    .width($(window).width())
    .height($(document).height());
};
```

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
