### ISSUE TITLE
Change or add arrows

### ISSUE THREAD

**Issue by avalonman** [lokesh/lightbox2#237]
Is it possible to show the arrows automatically when creating a multiple image slideshow and also have the arrows appear outside of the image area

**Comment by lokesh** [comment]
Old issue, but I want to chime in for others who might be looking for similar behavior.

Find the following code in lightbox.js:

```js
      var alwaysShowNav = false;
      try {
        document.createEvent('TouchEvent');
        alwaysShowNav = (this.options.alwaysShowNavOnTouchDevices) ? true : false;
      } catch (e) {}
```

Change to:
```js
      var alwaysShowNav = true;
```
