### ISSUE TITLE
Error when file not exists

### ISSUE THREAD

**Issue by standus** [lokesh/lightbox2#238]
Hi,
please fix bug which generate script error when image file physically not exists. Script prepare image prewiev without image and user can not do anything. Then is possible only reload page or move back.
Thank you

**Comment by lokesh** [comment]
Quickly chiming in on this old issue.

This is a nice-to-have but I will keep it the responsibility of the developer and not the script to catch broken image links.

**Comment by standus** [comment]
This can happen many ways: when bad connection, when file is deleted with other user and actual user have opened old content, etc.
When Ifound this issue, believe me that many people have same problem without reporting it.
