### ISSUE TITLE
I created a pull request to cdnjs

### ISSUE THREAD

**Issue by fyears** [lokesh/lightbox2#243]
cdnjs is a free and public cdn service that allow people to submit js and css libraries.

Since lightbox2 is free for use in both personal and commercial projects, I think it's ok and appropriate to distribute it via a cdn. If @lokesh disagrees, please contact me or contact cndjs via GitHub, and I would try to remove it as soon as possible.

I created a pull request at https://github.com/cdnjs/cdnjs/pull/3360 . 

Hopefully we can use lightbox2 from http://cdnjs.com/ soon.

And, to @lokesh , if you are interested, you can submit the newer version by yourself in the future. After all, you are the author and you know when it gets updates. :-)

**Comment by lokesh** [comment]
Closing out old issues.

Thanks for the help!
