### ISSUE TITLE
Change images for DataUri

### ISSUE THREAD

**Issue by matheuslc** [lokesh/lightbox2#245]
I think that's a better a idea use DataUri for Lightbox 2 images.

Pros:
A better organization
Less requests
Peoples have different file structures. When add lightbox, move images for his directory, have to change the path in css. That's not good. I think Data Uris solve this.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
