### ISSUE TITLE
Another href?

### ISSUE THREAD

**Issue by Rayuth** [lokesh/lightbox2#247]
I would like to know if it possible.
When you click on some text it uses an <a> tag and opens up a popup with an image.
I want to know if once you are in the popup, you can click on the image again while in the popup to open a link again.
Is this possible? and if so, how?

I apologise if this is in the wrong area.

**Comment by lokesh** [comment]
Closing out old issues.

It is not possible at this time to make the image a link out-of-the-box.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
