### ISSUE TITLE
Orientation in exif tags is not respected

### ISSUE THREAD

**Issue by KingDuckZ** [lokesh/lightbox2#249]
Hello, I'm not sure this is an issue with Lightbox itself or if I'm doing some configuration wrong. Possibly it's related to issue 206, though I see no mention of exif data in there.

In the gallery on my blog (http://duckz.serveblog.net/risorse/foto/francia/) you can see all the thumbnails have the correct orientation. Specifically, the second and third picture have been taken with my camera rotated by 90°. If you download the full-size image, you can run "exiftool <path_to_the_image> | grep -i orientation" to visualize the orientation info saved in the exif tags. Normally programs automatically rotate pictures based on that info; I tried accessing the direct link (http://duckz.serveblog.net/risorse/foto/francia/P1831_21-02-10.jpg) with Opera, Konqueror and Firefox and all of them show the Eiffel Tower with the correct orientation. Gwenview also shows it corrected, and Gimp asks if I want to see it raw or rotate it. Even the thumbnails are correct as the program that generated them automatically rotated the originals (so no exif tag in those afaik http://duckz.serveblog.net/risorse/foto/francia/thumbs/P1831_21-02-10.jpg). However when you click the image in the gallery and Lightbox pops up, you can see the orientation is wrong. How can this problem be fixed without me having to manually edit this kind of pictures?

**Comment by jer-tx** [comment]
Given that browsers still don't respect EXIF information within html tags for orientation, can we get native support for this?

**Comment by angerangel** [comment]
It isn't a browser problem, it's lightbox related.
If you try with this image: http://www.maxvessi.net/uffizi/pictures/20151128.JPG , you'll see that browsers show it correctly rotating it, but the lightbox plugin show it wrongly not rotated.

**Comment by angerangel** [comment]
Probably this script would resolve the issue: https://gist.github.com/runeb/c11f864cd7ead969a5f0
