### ISSUE TITLE
Light Box over Light Box

### ISSUE THREAD

**Issue by manan1099** [lokesh/lightbox2#250]
I have a form which is generated on a Light Box. Form Contains an Image which uses your light box code. On clicking The image, it gets enlarged behind the form generated on light box. I know z-index can fix the issue but want some reliable guide lines from your side. Thanking you.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
