### ISSUE TITLE
Lightbox errors  - v2.7.1

### ISSUE THREAD

**Issue by DickBlox** [lokesh/lightbox2#253]
Lokesh:   Lightbox is great - many thanks.    I've used it to zoom images in my local Art Club site.

But occasionally the white border round the zoomed image is partially missing.

I checked lokeshdhakar.com/projects/lightbox2 using 
           http://www.htmlhelp.com/tools/validator/
and     http://jigsaw.w3.org/css-validator/

Both showed up quite a few errors.     Similar / same errors using v2.6.

I'd much appreciate it if you could have a look sometime.

Thanks,

                      Dick

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
