### ISSUE TITLE
Adding additional content to an image

### ISSUE THREAD

**Issue by codecowboy** [lokesh/lightbox2#256]
Is this still the official line on custom content? http://stackoverflow.com/questions/5729082/add-custom-html-to-lightbox2

Just looking for confirmation or a method for adding an additional div within the caption area.

**Comment by lokesh** [comment]
Closing out old issues.

For the record, yes, Lightbox is not allowing complex content addition out-of-the-box and is remaining a streamlined image viewer. It will display captions and some navigational items, but not much else.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
