### ISSUE TITLE
Unable to display large pixel image

### ISSUE THREAD

**Issue by WeeHong** [lokesh/lightbox2#259]
Hello there.

Thank you for creating Lightbox library.

I face a problems that large pixel images cannot display properly.

My image width and height is 1004x1467 .

But the image unable to display in full width and height. Seen like all the width and height had been divided by 2.

Can I solve this issue? Because if the image is too small, users unable to read the content inside the image.

Thank you very much.

**Comment by lokesh** [comment]
Closing out old, inactive issues.

FYI... there was a bug in earlier versions of Lightbox that affected the width of images after the first. This has since been resolved and might have been related.
