### ISSUE TITLE
auto change?

### ISSUE THREAD

**Issue by Ryjobo** [lokesh/lightbox2#262]
is there a way to make these images in the lightbox cycle automatically? if so can someone help me with the code?

**Comment by lokesh** [comment]
Closing out old issues.

No auto-play available out of the box for Lightbox, sorry.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
