### ISSUE TITLE
automatic (re)size

### ISSUE THREAD

**Issue by anonemuss24** [lokesh/lightbox2#263]
I added a fullscreen button(native fs) to my light box and there appeared a problem.....   the lightbox (incl img) isnt resizing :/ ......  so may i ask if any1 knows a solution which auto resizes the lb .... also useful if some1 changes windows size of the browser.

Greetings,
Anonemuss24

**Comment by lokesh** [comment]
Closing out old, inactive issues. Please reopen with more details if appropriate.
