### ISSUE TITLE
Gallery Right / Next Image Arrow Button Appearing Below Images

### ISSUE THREAD

**Issue by nickck20030** [lokesh/lightbox2#266]
Hi,

I have a gallery working properly besides the fact that the right/next image arrow button is appearing well below the enlarged images despite the left button to go to the previous image working.
I've never had this issue with previous galleries and the code for this gallery is an exact replica of a currently working gallery in another HTML file.

![a](https://cloud.githubusercontent.com/assets/8083487/3489867/50f3f616-054b-11e4-9591-18e061257451.png)

**Comment by lokesh** [comment]
Closing out old, inactive issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
