### ISSUE TITLE
Map area

### ISSUE THREAD

**Issue by Nesales** [lokesh/lightbox2#267]
Hy .

Sorry for my english because i'm french.

I would like to use your code on an picture map with <area> but I can't change the index to achieve this is starting in html. 

How should I do? 

Thank you in advance

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
