### ISSUE TITLE
no margin or padding 

### ISSUE THREAD

**Issue by ajaywankhare** [lokesh/lightbox2#268]
![img-20140712-00023](https://cloud.githubusercontent.com/assets/8144558/3562126/dfa3d1ac-09e1-11e4-95c5-066384f977ef.jpg)
i dont want this space at starting of the image 
i dont understand how to edit it
please help
my email - ajaywankhare@yahoo.com

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
