### ISSUE TITLE
Any way to control the image size?

### ISSUE THREAD

**Issue by dmitriz** [lokesh/lightbox2#270]
The demo images expand nicely to make use of the screen but I get them too small on my site (http://33hotels.com).

Is there any way to control their size and location to make better use of the screen?

**Comment by maoanz** [comment]
You can probably add some jquery code to change the css : 
Here a pseudo example: 
$(document).ready(function(){
          // do something to detect image ratio, and calculate to new width and height
          var width: xxx; 
          var height : yyy; 

          // find in firebug the name of the container and image
          // and set the css by jquery. 
          $('.lb-outerContainer').css({
                 minWidth: xxx; 
                 minHeight: yyy; 
           });
	   $('.lb-outerContainer img').css({
		 minWidth: xxx; 
                 minHeight: yyy; 
	   });
});
