### ISSUE TITLE
Disable click event...

### ISSUE THREAD

**Issue by harish118** [lokesh/lightbox2#271]
hi,

Your lightbox plugin works amazingly well. But I have one little thing that I hope you can clarify. I am programmatically opening the image, and so I do not want the mouse clicks to close/hide the image. I have been able to use "disableKeyboardNav" to disable the keyboard navigation/closing but I was wondering how to disable the mouse clicks as well? Btw if I am using "disableKeyboardNav" , do I set it in this function Lightbox.prototype.showImage = function() { or do I set it in the options?

Thanks a ton,
M&M

**Comment by lokesh** [comment]
Closing out old, inactive issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
