### ISSUE TITLE
Get the lightbox image to show correctly with a scrolling page design?

### ISSUE THREAD

**Issue by shelthegreat** [lokesh/lightbox2#272]
I have a scrolling web design, everything on one long page. The lightbox works, but its way at the bottom of the current view and cut off. If you try to adjust by scrolling the page behind it moves but not the lightbox image. Is there a way to get it to view correctly in the present viewing space on a scrolling page design?

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
