### ISSUE TITLE
Move Close X to Top Right

### ISSUE THREAD

**Issue by rmmcclay** [lokesh/lightbox2#275]
Not really an issue but a question: I tried through css to move the Close [X] image/link.  I can move it, but then it's not clickable anymore.  Any ideas?

**Comment by enderoe** [comment]
I think it will be a good option to modify the position of the close button as well.

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still of interest, please make a note and I will reopen and investigate. Thanks.
