### ISSUE TITLE
Cannot set options outside the script?

### ISSUE THREAD

**Issue by phts** [lokesh/lightbox2#282]
Hello,

I was surprised but it seems that it's impossible to set custom options for `Lightbox`.

The only way to set custom options is to edit `LightboxOptions` class in original `lightbox.js` file. Editing `lightbox.min.js` is almost impossible so benefits from using this file disappear.

`Lightbox` is started during loading the whole script and do not accept any options from outside. It's even impossible to override `options` or `LightboxOptions` variables because they have own scope. It's even impossible not to start the `Lightbox` initially.

So have I to use predefined options? There is no convenient way to set options except editing original script, really?

**Comment by lokesh** [comment]
Old issue. But for the record, an easier way to set options has since been added:
```
  lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    })
```
http://lokeshdhakar.com/projects/lightbox2/#options

The API for the plugin is still limited and that is something I am hoping to open up in the next major release.
