### ISSUE TITLE
Trigger off <img> instead of <a>?

### ISSUE THREAD

**Issue by bobrocke** [lokesh/lightbox2#285]
Is there a way to trigger Lightbox 2 from a class assigned to an `<img>` tag as opposed to a `<a>` tag?

**Comment by lokesh** [comment]
Closing out old issues.

Requiring an `<a>` tag was intentional for accessibility purposes.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
