### ISSUE TITLE
Disabling Thumb From Loading Lightbox

### ISSUE THREAD

**Issue by blarche** [lokesh/lightbox2#286]
I want to create a set of images, however, the set of images that I am trying to create are thumbnails that open the larger image in a "primary" section of the page.  When the "primary" image is clicked, I want to the lightbox to popup.  From there, I would like to have a slideshow of all thumbs.  Basically, I want to disable the thumbs from opening a lightbox but enable the primary image to open a lightbox and loop through all images (thumbs).  Here is my site so you can see what I mean:

http://upcars.com/new-site/find-vehicle/vehicle-details.asp?v_id=31005

Thanks in advance!

**Comment by lokesh** [comment]
Closing out old, inactive issues.

If this issue still persists, let me know and I will reopen and review. Thanks.
