### ISSUE TITLE
Close button opacity hover state makes clicking finicky

### ISSUE THREAD

**Issue by colemanfoley** [lokesh/lightbox2#290]
The opacity rule in .lb-close:hover seem to be making clicking the X tricky. If I comment it out, my clicks on the X work as I expect them to. If I leave the opacity rule in, sometimes clicking the X works, sometimes it doesn't. Weird, right?

Chrome 36.0.1985.125
Mac OS 10.9.4

Same thing happens on Firefox 30.0, by the way.

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
