### ISSUE TITLE
Add thumbnail navigation to slideshow

### ISSUE THREAD

**Issue by lefty55104** [lokesh/lightbox2#291]
I need a way to display all of the images within the lightbox gallery as thumbnail navigation. For this particular project, I need the thumbnails in one line to the left of the main image that can scroll on its own. It would also be helpful to be able to have a caption or text to go over the image. 

But on a basic level, I need thumbnails to go along with the lightbox gallery.

**Comment by lokesh** [comment]
Closing out old issues.

The addition of thumbnails is out of scope for v2.x of Lightbox. I'll evaluate for the next major release though.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
