### ISSUE TITLE
Main image swap?

### ISSUE THREAD

**Issue by badyani** [lokesh/lightbox2#292]
Hi, can anyone direct me to an example of the lightbox where there is a main image and it swaps when you click on the thumbs, but opens into the lightbox when you click on the main image? 

Thank you for your help, its really appreciated.

**Comment by lokesh** [comment]
Closing out old issues but wanted to chime in real quick. I haven't seen examples of the Lightbox script modified for this feature. But it is an interesting idea. I'll take a look into it.
