### ISSUE TITLE
Speed up with velocity.js

### ISSUE THREAD

**Issue by ghost** [lokesh/lightbox2#295]
I use the lightbox from the start but haven't had a look for a while.
With all lightbox these days using css transitions but no one find using velocity.js to replace just the jquery.animate....

So, I changed the animations to use velocity.js and it works lots faster, probably even faster than css transitions.

However, it would be great to do that in the main version.

Thanks lokesh

**Comment by lokesh** [comment]
Closing out old issues. Using Github Issues for bugs only now. Thanks.

I'll re-review UI performance when I begin working on the next major version of Lightbox v3 ( [Roadmap](https://github.com/lokesh/lightbox2/blob/master/ROADMAP.md)).
