### ISSUE TITLE
Bower package is 7.7 MB. set only required files in bower

### ISSUE THREAD

**Issue by surajajency** [lokesh/lightbox2#297]
This can be reduced to only required files.
![screen shot 2014-08-15 at 4 12 38 pm](https://cloud.githubusercontent.com/assets/1841224/3932347/e80983ea-2468-11e4-956d-5e1bb9afb71f.png)

**Comment by lokesh** [comment]
This is being fixed now. All prior releases and the demo page were included in the Bower package previously. Oops.
