### ISSUE TITLE
Doesn't work on my site in IE9

### ISSUE THREAD

**Issue by Essentie** [lokesh/lightbox2#300]
http://www.tegola.ru/production/tile/page1.php
in IE9 or IE10 compability mode - doesn't work:(
Will be very much glad for any assistance in this problem...

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.

**Comment by Essentie** [comment]
Yes. The problem does still exist
