### ISSUE TITLE
data-title option issue

### ISSUE THREAD

**Issue by developer-prosenjit** [lokesh/lightbox2#301]
If i set data-title=""It's About Your Stage Not Your Age" Headgardeners in the Leader August 2013"
or 
data-title='"It's About Your Stage Not Your Age" Headgardeners in the Leader August 2013'

Lightbox caption not display properly. How can I set custom element for data-title

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
