### ISSUE TITLE
Main CSS dependency missing  on bower.json

### ISSUE THREAD

**Issue by clabnet** [lokesh/lightbox2#302]
The dependency of css is missing v. 2.7.1.
It is simple for you, only add the second line on bower.json and .bower.json files
. . .
   "main": [
        "js/lightbox.js",
        "css/lightbox.css"
    ],
. . .
It ensure the correct insert of css file with automatic bowerInstall grunt task.

Thank's,

**Comment by deerawan** [comment]
+1

**Comment by lokesh** [comment]
This has been fixed. Thanks.
