### ISSUE TITLE
lb-outerContainer doesn´t resize correcltly

### ISSUE THREAD

**Issue by EvalTracker** [lokesh/lightbox2#304]
The screenshot shows my problem.
![unbenannt](https://cloud.githubusercontent.com/assets/6358523/4102168/04eaa370-311d-11e4-998a-24d2ea5adf20.jpg)

The outer Container is to small and doesn´t fit. I found out, that the size of the outer container is exacly the size of the image. So the width and the height needs to be two times the width of the padding-border bigger. How can i fix that? Is it a problem in lightbox.min.js or in lightbox.css?

Thank you.

My site: http://traunviertler-traunwalchen.de/chronik.html (at the bottom of it)

**Comment by smokingcinnamonsticks** [comment]
I also have this issue... it's hit + miss... no pattern detected for what causes it. Anyone resolved this yet? 

Cheers!

**Comment by lokesh** [comment]
Closing this issue as I have not heard any recent reports.

If you are still seeing it happen, please post a link and I will reopen this issue review. Thanks.

**Comment by Trost123** [comment]
Still seeing this happen. How can I collaborate?

**Comment by lokesh** [comment]
@Trost123 are you able to share a link so I can inspect the issue? Also, what browser are you using and which version of Lightbox. Thanks.

**Comment by Trost123** [comment]
Here is the [link](http://salon.greys.com.ua/).
I'm using "lightbox2": "^2.8.2" (bower).
The issue happens in latest Firefox, IE.
In Chrome it looks fine.

**Comment by lokesh** [comment]
@Trost123 Try moving the loading of `lightbox.css` above the loading of `lightbox.js`. That should fix it.

I'm making an update to the script in the next release so that you will be able to load these files in any order with out issue. Till then, try the above.
