### ISSUE TITLE
Video & iFrame Support

### ISSUE THREAD

**Issue by vicmandesign** [lokesh/lightbox2#308]
Hi, it would be nice if the plugin also support video and iFrame (like youtube, vimeo)

**Comment by justinmasuga** [comment]
That would be awesome. Has anyone figured out a workaround? Like adding a link or something to the image.

**Comment by lokesh** [comment]
There are alternative scripts that allow you to show videos and html content. The plan is to keep Lightbox focused on displaying images and continue improving this experience. Thanks.
