### ISSUE TITLE
Caption: Using image title, not link title

### ISSUE THREAD

**Issue by elbsurfer** [lokesh/lightbox2#315]
Hello,
How can I change lightbox in order to take the value of the title or alt of the <img> tag as caption in the slideshow and not to use the title value of the link which capsules the <img> tag?

Does anybody know?

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
