### ISSUE TITLE
iOS prev/next opacity

### ISSUE THREAD

**Issue by fishy1892** [lokesh/lightbox2#318]
On other browsers the opacity is used to vary the prev/next arrows transparency as well as the close icon. On iOS Safari the closed setting is obeyed but the prev/next are either on or off and neither the main opacity (.lb-nav a.lb-prev for example) or the hover value (as there's no hover state in iOS) are!

Is there another setting that can be set to vary the opacity on iOS?

**Comment by lokesh** [comment]
Closing out old issues.

FYI.. I'm working on a major overhaul of the mobile web experience of Lightbox in the next release, v3.0. Expect a lot more polish for mobile this time around!
