### ISSUE TITLE
add 'pull from Flickr' function...

### ISSUE THREAD

**Issue by prettykiller** [lokesh/lightbox2#319]
I'm not a back end/php/mysql/whatever you need to write these kind of things expert, and thus have a hard time trying to find out how to do this... but I'm wondering if someone has written a function to incorporate a flickr gallery into this lightbox.  I love lightbox's functionality, but I would love even more if I could tell a client that they can just upload their new photos to flickr and have them go live to their site.  Help?  Thank you!

**Comment by lokesh** [comment]
Closing out old, inactive issues.

I can reopen if this is still of interest for anyone.
