### ISSUE TITLE
IE loads only half of base64 images

### ISSUE THREAD

**Issue by arrudaje** [lokesh/lightbox2#324]
I have images stored in my database and I am loading them via base64 on my page. They are thumbnails so Lightbox would show them full size. Chrome and Firefox deal perfectly with this situation, whereas IE doesn't. In IE, images are loaded flawlessly throughout the page, however, when I click on one of them to open Lightbox, the image is frustratingly loading halfed. Just the very top of the image loads, and then it starts fading to black or even green. Here's one example:

![untitled](https://cloud.githubusercontent.com/assets/5851448/4396432/ecb701b0-4434-11e4-9d91-a3d662a14798.png)

Is it a solvable issue?

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
