### ISSUE TITLE
Image documentation

### ISSUE THREAD

**Issue by chillichicken** [lokesh/lightbox2#328]
Where is the image with the light house at the bottom of the cliff taken ?
I am missing some serious content documentation here...

**Comment by lokesh** [comment]
@chillichicken old question, but I wanted to chime in about the lighthouse on the cliff photo that is on the Lightbox2 demo page:
http://lokeshdhakar.com/projects/lightbox2/

It is a lighthouse in Point Reyes California:
https://www.google.com/search?q=point+reyes+lighthouse&safe=off&espv=2&biw=1152&bih=1174&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIpLHm4YWWxgIVjC6ICh1ttAxD
