### ISSUE TITLE
Running a custom function on image click

### ISSUE THREAD

**Issue by dant89** [lokesh/lightbox2#329]
How can I run some additional jQuery code on click of the element that has data-lightbox="initiate"?

I'm looking to combine spritespin (http://spritespin.ginie.eu/) so that I can spin the images inside the lightbox upon initialisation, just struggling with step 1!?

Thanks!

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
