### ISSUE TITLE
Resizing lightbox images

### ISSUE THREAD

**Issue by Kakumei** [lokesh/lightbox2#331]
The large images that come up from my thumbnails are too small to read the text.  I tried resizing the files but lightbox makes them a standard size I can't control.  How can I alter this?

**Comment by lokesh** [comment]
Closing out old issues.

Lightbox fits images in the viewport by default. Set ` fitImagesInViewport` option to false in `lightbox.js` if you'd like to show images at full size w/o any resizing.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
