### ISSUE TITLE
Lightbox is triggering default action on MVC controller when loading.

### ISSUE THREAD

**Issue by harrisonbs** [lokesh/lightbox2#335]
This issue occured for me when using lightbox against an MVC 2 application. I was getting the following exception in my application exception handler

System.Web.HttpException: A public action method 'Internal' was not found on controller 'XXX Controller name'

Internal is the default action that was setup in the routing tables. After playing around with it, I realised that it was being triggered by the lightbox library, so I started working out where. It turns out that it is in the Lightbox.prototype.build function.
Specificially the html that is appened to the body - "&lt;img class='lb-image' src='' /&gt;"
The empty string was causing the img src to be loaded based upon the calling page's default controller action.
The fix I have implemented in my code was to change
&lt;img class='lb-image' src='' /&gt;
to
&lt;img class='lb-image' src='#' /&gt;

It all seems to work.

**Comment by lokesh** [comment]
Closing out this old issue.

It should have been resolved by https://github.com/lokesh/lightbox2/pull/280
