### ISSUE TITLE
lightbox.css body:after trigger ie8 compatible mode

### ISSUE THREAD

**Issue by beherca** [lokesh/lightbox2#340]
See 

```
body:after {
  content: url(../img/close.png) url(../img/loading.gif) url(../img/prev.png) url(../img/next.png);
  display: none;
}
```

Below code will trigger compatible mode on ie8

```
 content: url(../img/close.png) url(../img/loading.gif) url(../img/prev.png) url(../img/next.png); 
```

below setting will be ignored

```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```

May I ask why you put content in body after? do you want to preload them to browser cache?
any better solutions?

**Comment by lokesh** [comment]
Closing out old issues.

Some info on the `body:after`. It is a _hack_ for preloading the assets. Though this causes some issues in IE8, because of the waning usage of this browser I will not be making any changes to accommodate.
