### ISSUE TITLE
How to add new line in text returned in function?

### ISSUE THREAD

**Issue by jimjiminy** [lokesh/lightbox2#344]
Hi.
I know it sounds stupid but I know nothing concerning javascript. I want to add some text on the following line:
_LightboxOptions.prototype.albumLabel = function(curImageNum, albumSize) {_
      _return "Image " + curImageNum + " of " + albumSize;_
    _};_
in order to put instructions to viewers. I have tried \n\r but it doesn't work. How can I show for instance:

**Image 4 of 6**
**Click right/left side of the image to see the next/previous image**

instead of 

**Image 4 of 6 Click right/left side of the image to see the next/previous image**

Thanks for a quick reply guys.

Jim

**Comment by lokesh** [comment]
Closing out old issues.

Sorry this didn't get a response. For the record, if you wanted to add a line break to the count label then you would need to do two things:
1. Add `<br />` tag into your albumLabel string
2. Replace the `.text()` call with `.html()` in the following line:
`this.$lightbox.find('.lb-number').text(labelText).fadeIn('fast');`

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
