### ISSUE TITLE
image lightbox always showing twice 

### ISSUE THREAD

**Issue by fredattack** [lokesh/lightbox2#345]
i everybody, 
since a long time i' m searching why my image are always showing twice after click!
i have modify the caption, change data-lightbox by rel:"lightbox...",
i 'm searching everywhere i can but don't find anything!
Maybe a setting in javascript.js but i m not a specialist!!
please help me

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
