### ISSUE TITLE
Open lightbox in full screen when called from an iFrame

### ISSUE THREAD

**Issue by And1m** [lokesh/lightbox2#348]
I generate a list of images from a db in an iframe, but when the image is clicked the larger image is displayed within the constraints of the iframe.  Could there be an option to display the larger image fullscreen (or the size of the browser window size)?

Thanks

Andy

**Comment by dondgitale** [comment]
I have the same problem, did you find a solution ?

**Comment by magnum79** [comment]
I have similar problem.
Bigger image opens inside iframe, everything fine, except vertical positioning, image sticked to the top of iframe instead of vertical centering on monitor.

**Comment by bencagri** [comment]
+1

**Comment by lokesh** [comment]
Closing out old issues.

re: Opening image in lightbox in parent window from child iframe
In the next major release, v3.0, which is in early stages, I'm investigating expanding the API to allow you to choose an element where the Lightbox component will be placed. I have limited experience with iframes but I will test if the iframe document can reference an element upstream in a mannert like this: `window.parent.document.getElementById('foo')`; tbd

If you still need help in the meanwhile, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

**Comment by aanders77** [comment]
@lokesh Thanks for your great work! I ran into this iframe problem today. Did you ever find a way to do this?
