### ISSUE TITLE
Callback to allow to customize the full image url?

### ISSUE THREAD

**Issue by ngonhan2k5** [lokesh/lightbox2#350]
It's very helpful if we have a callback that allow customizing the full image url. 
For example the full url can be generate from thumbnail url base on a naming rule.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
