### ISSUE TITLE
How do i make a swipe next image or prev image

### ISSUE THREAD

**Issue by kurodz** [lokesh/lightbox2#356]
As title , swipe function like this ? 

this.$lightbox.find('.lightbox').on('swiperight', function() {
        if (self.currentImageIndex === 0) {
          self.changeImage(self.album.length - 1);
        } else {
          self.changeImage(self.currentImageIndex - 1);
        }
        return false;
      });

**Comment by lokesh** [comment]
Dupe of #233

**Comment by super-summer** [comment]
这个swiperight还要引入jquery mobile 文件，
