### ISSUE TITLE
Images in Lightbox are showed multiple times in combination with bxSlider.

### ISSUE THREAD

**Issue by JohnVermeulen** [lokesh/lightbox2#357]
Hi everybody,
I am using Lightbox with an image set with 3 images. When i click on an image and cycle through the images in Lightbox each image is showed three times. Also the image counter on the left bottom is showing a total number of nine images while infect there are only three images as mentioned
.
I'm using Lightbox in combination with bxSlider. Every image in bxSlider has a link that will open Lightbox. I noticed that the problem with the image numbers in Lightbox is only appearing in combination with bxSlider. So when I don't use the bxSlider js everything works fine but the combination seems to be the trouble.

This looks a little like thread #345 but I'm not sure.
Has anyone experienced the same problem or knows how this can be solved?
Thanks in advance.
John

**Comment by cdchen** [comment]
I have the same problem. 

I am using the bxslider 4.1.1 and lightbox 2.7.1. When creating bxslider with infiniteLoop option as true, lightbox always add image to album repeat 2 times, if infiniteLoop as false, the count of images is correct.

**Comment by ngonhan2k5** [comment]
Because with infiniteLoop enable, bxSlider copy (doubling) the images DOM to prepair for loop display.

**Comment by maguijo** [comment]
Thank you dalai-lamia and cdchen and ngonhan2k5 for the answer to my problem as well!

**Comment by Roemer** [comment]
My solution for this problem is to remove the data-lightbox attribtue of all clones. I do this after the slide has loaded with this code:
```javascript
onSliderLoad: function(){
    $(".bx-clone").children().removeAttr("data-lightbox");
}
```

**Comment by rinabh** [comment]
Roemer's solution work for me, when used lightbox with flexslider
