### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by DavetheNacus** [lokesh/lightbox2#363]
Hello.  My apologies if this is repetitive, but I cannot get Lightbox 2.7.1 to do a continuous loop.  I did what you instructed here: https://github.com/lokesh/lightbox2/issues/131 .  But to no avail. I really like what you have created and would prefer to use it, but I also need the user to be able to loop through the images as much as they want without stopping. Is there something more that I should be doing that I am not doing?

Thank you,

Dave

**Comment by KaptnKonay** [comment]
If you want to make a loop in the image slideshow in v2.7.1 you need to change  the following in your js file:

First line:
"this.wrapAround=!1" to "this.wrapAround=!0"

1 = no loop
0 = Loop

I hope I could help you!

**Comment by DavetheNacus** [comment]
That did it!  THANK YOU!




Dave Damianakes
+1 510.317.6306
www.bayareatechwriters.com

**Comment by KaptnKonay** [comment]
You're welcome! Nice that I could help you! ;-)
Have nice day!

**Comment by djvov** [comment]
thank you!
