### ISSUE TITLE
No lightbox.sass in the sass folder

### ISSUE THREAD

**Issue by andrearinaldispotsoftware** [lokesh/lightbox2#366]
Hi,

congrats for the very good work, but.. installing from bower, no lightbox.sass gets placed in the /sass folder.

Is something missing.. or am I doing something wrong?

Thanks in advance!
![lightbox](https://cloud.githubusercontent.com/assets/6502044/5525464/8e5e1c8c-89e6-11e4-8908-470e3b6b8eb6.png)

**Comment by lokesh** [comment]
```lightbox.css``` was written with plain old CSS and only the demo/docs page used SASS to compile its CSS. This has now been made more clear as all SASS (along with the demo page) have been removed from the repo.
