### ISSUE TITLE
Option for Download

### ISSUE THREAD

**Issue by rajasekar-i2i** [lokesh/lightbox2#368]
Download option for the image would be very helpful. If the users like to download the current image, there is not option for it. We can provide it by some property  while creating the image URL in order to have download for it.

**Comment by gauravmanral** [comment]
i also want this. did find any help..??

**Comment by rajasekar-i2i** [comment]
No Gaurav, I did not get any help in this issue. This download option is not yet done in my project.

**Comment by gauravmanral** [comment]
I found it in support forum just now.
hre is the link:
https://github.com/lokesh/lightbox2/pull/323

**Comment by rajasekar-i2i** [comment]
Thanks Gaurav, I will use that code. But it is not published as a version, They merged the code but version is not updated. @lokesh , Can you release as a new version(2.7.3). 

Once again thanks a lot Gaurav.
Thanks in advance Lokesh.  :)

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
