### ISSUE TITLE
Can't load images

### ISSUE THREAD

**Issue by sancy007** [lokesh/lightbox2#371]
I get this problem after I upload the script on my webserver? But on my local computer it all works fine. Can some one help me with this issue ?

When I press an image so that the lightbox should appear, it get's started but it keeps showing the load icon instead of showing the images.

![naamloos](https://cloud.githubusercontent.com/assets/10463763/5680219/6a3675a2-980a-11e4-912e-9c9e01d62235.png)

**Comment by MediaCarbon** [comment]
Two most likely problems:
The images aren't uploaded to the server.
The paths are slightly different on the server than on your local computer.

Chris Leeds
MediaCarbon, Inc.
(Mobile) 347-422-7266 | 347-4CARBON
(Toll-free) 800-591-5160
(Skype) ChristianLeeds
(FB) http://Facebook.com/ChrisLeeds
________________________________

**Comment by sancy007** [comment]
But i have checkes the script on the html file and addept it also to the place where the images are stored. And still it gives the same problem.

**Comment by sancy007** [comment]
Is there any where else that i should look ?

**Comment by sancy007** [comment]
Maybe you can check it on http://www.hsgroup.be/referenties.html

**Comment by sancy007** [comment]
Okey, i already found the issue, the extensions of the images where .JPG and i had .jpg in the script.

**Comment by MediaCarbon** [comment]
I was just looking at it and was heading in the same direction.  The i-frame threw me off a little.
Congratulations!

**Comment by sancy007** [comment]
thanks

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
