### ISSUE TITLE
shadow background problem with android 4.4.4 webview

### ISSUE THREAD

**Issue by caBBAlainB** [lokesh/lightbox2#372]
Hello,
I have a little problem with android 4.4.4 webview, which is supposed to be the Chrome for Android (https://developer.chrome.com/multidevice/webview/overview) engine.
When I click on the thumnail, the popup is opened with its black, semi-transparent background but the second time I click any thumbnail, the popup is opened (more quickly) with a full transparent background.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2).
