### ISSUE TITLE
Sometimes pulls wrong description/image number

### ISSUE THREAD

**Issue by garethlp** [lokesh/lightbox2#373]
Sometimes, in IE8, when clicking on a thumbnail, or clicking on the full-sized image or back/next arrows, in my gallery, the photograph will load but it shows the image number and description for the image before or after it.

**Comment by lokesh** [comment]
Old issue, but I wanted to chime in. I have done some IE8 testing and have not been able to reproduce this issue.

Can you post a link to the issue or the relevant code. I can reopen this issue then. Thanks.
