### ISSUE TITLE
https://github.com/lokesh/lightbox2/blob/master/css/lightbox.css#L128 probable mistake

### ISSUE THREAD

**Issue by MunifTanjim** [lokesh/lightbox2#375]
https://github.com/lokesh/lightbox2/blob/master/css/lightbox.css#L128
I think there's been a mistake. Wouldn't that be 34% ?

**Comment by lokesh** [comment]
Old issue, but I wanted to chime in quickly.

This is not a mistake. When an image is loaded with Lightbox, the 'prev' navigation width is ```34%``` but the 'next' navigation width is ```64%```. Moving forward to the next image is the most common action and the click target for this is intentionally made wider.
