### ISSUE TITLE
Configure Lightbox to not open when clicking-and-dragging within scroller

### ISSUE THREAD

**Issue by syg6** [lokesh/lightbox2#376]
I am using lightbox to open up a large version of images. These images are within a smoothDivScroll, and that smoothDivScroll is configured to only scroll when you click on one of the images and drag to the left or right.

The problem is that when you mouseup, lightbox opens up. Of course it does, that's what I configured it to do!

My question -- is there any way to tell lightbox ***not*** to open ***if and only if*** I have dragged the image between mousedown and mouseup?

**Comment by arhad** [comment]
Reassign 'onmouseup' event handler to 'onmouseclick'.

**Comment by syg6** [comment]
Actually, this is a non-issue. I mistakenly posted here when in fact the Lightbox I was using was a jQuery plugin version of this library. I got rid of the plugin, used this library instead, and all is well.

**Comment by syg6** [comment]
Hi, thanks for the response.
Actually it's no longer an issue. I just updated my post on github. I was using a jQuery plugin version of the Lightbox library. When I substituted it for the actual library itself, it works fine.
Thanks again. 

     On Friday, January 30, 2015 4:51 PM, Oleg Yarigin <notifications@github.com> wrote:
   

 Reassign 'onmouseup' event handler to 'onmouseclick'.—
