### ISSUE TITLE
how do I end lightbox and start new one?

### ISSUE THREAD

**Issue by ghost** [lokesh/lightbox2#377]
I want to create different light boxes for each different subject. Now there is one lightbox but he's showing all the pictures of all the different subjects..
Thx

**Comment by arhad** [comment]
It is well explained on [a site of the project](http://lokeshdhakar.com/projects/lightbox2/). Shortly, you must provide 'data-lightbox' property, one shared between every photo of a "subject", so you get as much unique property values as a number of your subjects. In addition, photos on different subjects may interleaved.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
