### ISSUE TITLE
Use "alt" arribute against of "data-title"

### ISSUE THREAD

**Issue by arhad** [lokesh/lightbox2#378]
For current version "data-title" of an `<a>` tag is used. I propose to take captions from "alt" attribute of nested `<img>`. This is more preferrable because we: 

1. Eliminate writing the same commenting text two times,
2. enforce users to provide valid alternate text for search bots and
3. get rid of one non-standard attribute.

**Comment by Lutacon** [comment]
What if we want the caption be different of the alt of the <img> ?

**Comment by quayle** [comment]
I suggest to make "alt" as default for title, and if "data-title" exists, to override default with it.

**Comment by lokesh** [comment]
Closing out old issues.

One point about titles/captions vs alt text. Alt text is used mainly for describing images to screen readers to help those with visual impairments and for SEO purposes. Title/Captions serve very different purposes. In most cases, you do not want to make visible your `alt` text as a caption.
