### ISSUE TITLE
Add lightbox features to "figure"/"img"/"figcaption" elements

### ISSUE THREAD

**Issue by gbordel** [lokesh/lightbox2#379]
I am absolutely new to lightbox, so... sorry if my comment is out of context.

¿What about associating "data-lightbox" attribute to the "figure" HTML element, and using "a" and "figcaption" inside, to show the image and the caption (now supported by the "data-title" attribute) respectively?

Thanks for Lightbox!.

**Comment by arhad** [comment]
Maybe because Lightbox is just a wrapper around a link to an image opening the link inside dedicated area instead of new page?

**Comment by lokesh** [comment]
Closing out old issues.

I'm putting a roadmap for the next major release, v3.0, and I've noted your suggestions regarding the use of `figure` and `figcaption`. I'll review to see if that makes the most sense vs other semantic markup.
