### ISSUE TITLE
Mobile device switch

### ISSUE THREAD

**Issue by andylaci** [lokesh/lightbox2#380]
is there some easy way to turn off lightbox on mobile device? on desktop it works briliant, but on mibile devices it allways take a lot of space and is lagging. I would be really happe if there was function like: mobile: off; I think a lot of users would appreciate it. On mobile device would work native open image in the same or new tab.. considered to target value

**Comment by arhad** [comment]
Why turn it off? I propose to introduce new (mobile-friendly) view. This one would be fullscreen.

It would be utomatically switched on mobile devices, or any device with small enough screen. Nowadays CSS allows it withous any JS code change.

**Comment by andylaci** [comment]
@arhad , this is even better solution...

**Comment by lokesh** [comment]
Closing out old issues.

In the [roadmap](https://github.com/lokesh/lightbox2/blob/master/ROADMAP.md) for v3 is a complete rewrite with a focus on mobile.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
