### ISSUE TITLE
Loading animation problem

### ISSUE THREAD

**Issue by SyphonicMarrow** [lokesh/lightbox2#381]
When I open a photo and then pres 2-3 times to load next image, Loading animation seems to be stuck. How can I fix this ?

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
