### ISSUE TITLE
ipad navigation arrows weirdness

### ISSUE THREAD

**Issue by syg6** [lokesh/lightbox2#382]
It seems that on iPads, initially the navigation arrows in the large versions of the images appear only when you mouseover, which is correct. But if you tap the right side of the image to go to the next image, the navigation arrow is always visible, without mouseover, on the next and all subsequent images until the last image in the set, where it isn’t displayed (because there are no more images).

This seems to be a bug. I would like the naviagation arrows to only appear on mouseover.

Has anyone else seen this?

**Comment by lokesh** [comment]
Closing out old issues.

This definitely could be a real bug. I'm not planning any more work on the mobile web experience for version 2.x of the script so I'm going to let the bug stand if it exists as it is minor.

I've made note of the issue though and I'll tackle it in v3.0 which I'm beginning work on. Thanks for reporting.
