### ISSUE TITLE
unique images

### ISSUE THREAD

**Issue by Redsmith24** [lokesh/lightbox2#384]
Maybe it is a feature request.
Using lightbox in a shop, I have a middle-sized product-picture and a row of thumnails. The thumbnails include also the first, the middlesized picture. A click on the images should open the lightbox with unique images. At the moment the first picture is shown twice.
If you think, this is the normal behavior, so I would like to have an option like unipueImages=true. Is this possible?
Thanks Luigii

**Comment by Redsmith24** [comment]
I hope it's not only my problem.

**Comment by martin-ko** [comment]
Hi,

I have the same feature request. Currently, any image is added to the gallery as often as you provide a link to it within your html. In order to change that , the function "addToAlbum" should only be called if that image/link is not part of the album yet (line 159 in lightbox.js). My own js skills are not yet sufficient to implement it :-(

Martin

**Comment by lokesh** [comment]
Chiming in a bit late. If issue is still relevant, can you clarify. I'm having a trouble understanding the request.

Once more details are provided I will reopen the issue and investigate. Thanks.

**Comment by Redsmith24** [comment]
We would like to habe no dublicated images in the album.
In the moment every link to an images creates an entry in the album. We want to link to an image in the gallery from different places without adding an images multiple times to the album.
I hope it is getting clearer now ;-)

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
