### ISSUE TITLE
Lightbox 2 image overlay not centered and overlapping description-screen shot attached

### ISSUE THREAD

**Issue by Drainediam** [lokesh/lightbox2#387]
Please see image. Does anyone know of a fix for this? Thanks!
![overlay_problem](https://cloud.githubusercontent.com/assets/10816867/6048144/5ad1554c-ac7c-11e4-8e75-9c4b9a8c0f5c.jpg)

**Comment by fragerbo** [comment]
I had the same troubles and I fixed it by playing with the CSS:

.lightbox a img {
  border: 8px;
}

or

.lb-container {
  padding: 0px;
}

**Comment by Drainediam** [comment]
Great, thanks a lot, appreciate it.

**Comment by Katamarino** [comment]
I had this same problem, and solved it using the fix from fragerbo. However, I now have no white border, like the demo has. The navigation arrows also do not show up. 

http://www.katamarino.co.uk/new_site/usa2012.php is where I am trying to use it; the problems can be seen there.

Can anyone assist? I have not changed any of the js or css apart from changing the path for the icons from "img" to "images" (I don't even know js to be honest!)

![image](https://cloud.githubusercontent.com/assets/11186780/6364394/3ebdf9d0-bc73-11e4-871f-7d2c77215bc7.png)

**Comment by Katamarino** [comment]
I had this problem, and fixed it with the same method. I now do not get the white border showing, however. I played around a little with different values of border and padding but with no luck. Does anyone know a fix?

![image](https://cloud.githubusercontent.com/assets/11186780/6364502/e7b84fd0-bc74-11e4-845e-7719826f9925.png)

http://www.katamarino.co.uk/new_site/usa2012.php
