### ISSUE TITLE
calling lightbox from within div

### ISSUE THREAD

**Issue by dondgitale** [lokesh/lightbox2#388]
so, I am no programmer... but wanted to use the lightbox script to show some photosets.
First my website was structured with iFrames, which then confined the lightbox within it. Duh ! Apparently there is a way around this problem, but I could not get it to work... and as I read that iFrames should be avoided anyway, I rebuild my site using just divs. But now when I call the lightbox from within the page that I load into the div on my main page, the lightbox is again confined inside the div !
so how can I make my lightbox break out of it ???

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
