### ISSUE TITLE
'Unable to get the value of property 'appendChild' in IE8

### ISSUE THREAD

**Issue by mikekrueger** [lokesh/lightbox2#389]
I have paired down a test page to the bare minimum. It works in every browser except IE8 (and less). All scripts and sheets are unaltered from the download package available on http://lokeshdhakar.com/projects/lightbox2/. The console does not show any errors prior to clicking the link (therefore, the there are no broken links or anything.)

`<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <title>Test</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel='stylesheet' href='lightbox.css' media='all' />
    </head>
    <body>
        <a href="image.jpg" data-lightbox="example-1">Test</a>
        <script type='text/javascript' src='jquery-1.11.0.min.js'></script>
        <script type='text/javascript' src='lightbox.min.js'></script>
    </body>
</html>`

**Comment by lokesh** [comment]
The 2.x versions of jQuery which Lightbox uses do not support IE8. 

I am working to remove the jQuery dependency from Lightbox and revert support for IE8 at that time.

**Comment by lokesh** [comment]
I changed my mind on this. Until I remove the jQuery dependency, which may take a bit of time, I am going to switch back to an older version of jQuery that supports IE8. This reversion is now in master.
