### ISSUE TITLE
Toggle lightbox with Javascript

### ISSUE THREAD

**Issue by MarioVillani** [lokesh/lightbox2#391]
Hi, is there a way to toggle the lightbox without using an <a> element?
I mean, something like $('#lightbox').open(img_to_open);
Thanks.

**Comment by DanyaDaro** [comment]
subscribe to the issue

**Comment by lokesh** [comment]
It's a hack but you can add a link that is empty to the page and then trigger a click on it via jQuery:
```
<a id="img" href="img.jpg" data-lightbox="img"></a>

<script>
$('#img').trigger('click');
</script>
```

I'm planning out what features to put in to the next major release of Lightbox, v3.0, and I'll definitely be exposing more methods to devs to initialize, open, close, and configure the script.
