### ISSUE TITLE
Creating a Watermark for large image view

### ISSUE THREAD

**Issue by ptfagan** [lokesh/lightbox2#393]
Hello, Can anyone possibly tell me how to create a single watermark for all images on a site using lightbox.js / lightbox.css.  Ideally, I would like the option to add either an image or text as an overlay. 

Any help would greatly be appreciated.  Thank you!! Tina

**Comment by NJWebDesign** [comment]
You could use CSS?  I use the following to overlay text on an image but it doesn't stop people simply right clicking and saving the image (which won't have the overlaid text or graphic).

As a rough guide...
The CSS:
.imagearea {width:640px;height:480px}
.overlay {position:absolute;visibility:visible;z-index:9999;color:#fff;font-family: Arial, serif;padding:20px;}

The HTML:
    <div class="imagearea">
        <div class="overlay">
            Overlaid text or transparent PNG watermark
        </div><! end overlay -->
        <img src="imagefolder/image.jpg">
    </div><! end imagearea -->

Hope that helps.
NJ

**Comment by ptfagan** [comment]
thank you!!!

**Comment by lokesh** [comment]
If you want to add a watermark directly to the image to prevent theft, rather than just something visually on top,it is possible using Javascript and the Canvas tag. Here is a script that does this: http://brianium.github.io/watermarkjs/

**Comment by simonbook** [comment]
I know this is an old thread, but I do it this way:

$(".imgClass").click(function() { 
   watermarkLightBox();
})

function watermarkLightBox(){
	$(".lb-container").append('<img src="/theme/default/images/logo1.png" class="lightBoxWaterMark img-responsive"/>');	
}
