### ISSUE TITLE
Occassional hairline displaying on iPad

### ISSUE THREAD

**Issue by greyscaleGD** [lokesh/lightbox2#395]
Is anyone else getting a broken hairline displaying to the left of the top left corner of some lightbox images when viewed on an iPad? I'm assuming it's a display bug?

**Comment by FoxtrotLima** [comment]
I've seen this on an iPhone. Sort of like a trail of pixels left behind after resizing. FWIW, I did not notice this behavior when using colorbox.

**Comment by greyscaleGD** [comment]
Thanks, FotxtrotLima. We're have a couple other issues, so perhaps Colorbox might be the answer.

**Comment by lokesh** [comment]
I am unable to recreate this issue. Can you post a link to the issue or the relevant code below. Once you do that I will reopen and investigate. Thanks.

**Comment by greyscaleGD** [comment]
Thank you for looking into this. The page is 

http://www.phyllisalter.com/test/fresco-retina-test.html <http://www.phyllisalter.com/test/fresco-retina-test.html>
