### ISSUE TITLE
thumbnail set width

### ISSUE THREAD

**Issue by fsteddie** [lokesh/lightbox2#396]
I was hoping there is a setting that can either be added or adjusted by me to set a standard width for image thumbnails in the lightbox. If this is confusing.... When I set up a gallery for the lightbox it displays the images all in a row as best it can. The row is left aligned but I want it to be square so that the gallery takes up the entire width of the div section. Is there a way for me to change the setting so that the images are a standard width or auto adjust them? Im looking in the code and nothing is jumping out at me.

**Comment by Maccapolo** [comment]
I am looking for similar info, my lightbox is used on Oscommerce site for products the main product image is half the width of the page, the thumbnail set is limited to half the width too. I cant seem to find the code to separate the two into different divs!

**Comment by lokesh** [comment]
Closing out old issues.

Lightbox doesn't offer thumbnails out of the box so I'm guessing you're referring to a variant of this plugin.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
