### ISSUE TITLE
loading problem

### ISSUE THREAD

**Issue by Policarpa** [lokesh/lightbox2#397]
wheni open the photo he never load the photo he satays loading, i dont know waht happend but i need help pls

**Comment by LesMcCutcheon** [comment]
Having the same issue, did you work out what it was?

**Comment by LesMcCutcheon** [comment]
My problem was I was leaving the href="#" on the a-tag as I didn't see the point for it, once this was added it worked :) Doh

**Comment by lokesh** [comment]
This issue is usually caused by an incorrect link to the image in the anchor tags ```href```.
