### ISSUE TITLE
Problem with Lightbox2 and Classic ASP repeat region - three sets of images?

### ISSUE THREAD

**Issue by NJWebDesign** [lokesh/lightbox2#401]
I have Lightbox2 set up on a page that calls images from a database using some Classic ASP:
http://www.tradmusic.com/tradmusic-festival-gallery.asp

There are 6 images in the recordset yet when I click on any of the images to enlarge, via Lightbox, Lightbox is reporting that there are 18 images available and it just loops the 6 images 3 times.

I've double checked the recordset, which returns 6 images.  Why is it multiplying them by 3?
Hoping someone can point out the obvious mistake.  Thank you.
NJ

**Comment by r3bify** [comment]
I'm having the same issue, I believe it has to do with an issue with their sets. It counts up all the images to add to the "total" images, regardless if it is part of the set or not.

**Comment by lokesh** [comment]
Old issue, but if anyone is still seeing an incorrect image count with Lightbox, please let me know and post relevant code or a link. Thanks.
