### ISSUE TITLE
Lightbox 2.7.1 and Flash Slideshow Wizard

### ISSUE THREAD

**Issue by tigerstime** [lokesh/lightbox2#402]
I had been using Lightbox 2.04 with individual images and I made the recommended js modifications to make it work with Flash Slideshow Wizard. I rarely use IE anymore, but the other day I checked out my site using IE 10, and I was getting all kinds of js script errors. I downloaded Lightbox 2.7.1, and the js script errors stopped. But the Flash Slideshow Wizard would no longer bring up images when clicked in a lightbox. Any recommendations?

Thank you.

Jason

**Comment by lokesh** [comment]
Sorry, I do not have experience with Flash Slideshow Wizard.

I am considering adding a slideshow/thumbnail tray into a future version of Lightbox which might meet your needs though.
