### ISSUE TITLE
Allowing only one a link to call lightbox

### ISSUE THREAD

**Issue by eggins** [lokesh/lightbox2#405]
Currently, I have a client with the weirdest setup store you could possibly imagine. 

Is it possible so that only one of the anchors when clicked, triggers the lightbox to fire, then can toggle through the group? Weird request, I know.

**Comment by webdesign4wien** [comment]
You can easy do it like this:
<a href="images/image01.jpg" data-lightbox="set01" data-title="Image 01"><img src="images/image01.jpg" alt=""></a>
<a href="images/image02.jpg" data-lightbox="set01" data-title="Image 02"></a>
<a href="images/image03.jpg" data-lightbox="set01" data-title="Image 03"></a>
<a href="images/image04.jpg" data-lightbox="set01" data-title="Image 04"></a>
<a href="images/image05.jpg" data-lightbox="set01" data-title="Image 05"></a>
<a href="images/image06.jpg" data-lightbox="set01" data-title="Image 06"></a>

**Comment by lokesh** [comment]
The above suggestion will work. :+1:

**Comment by eggins** [comment]
Thank you! :)
