### ISSUE TITLE
How to force image cache refresh ?

### ISSUE THREAD

**Issue by vitia2** [lokesh/lightbox2#407]
Steps to reproduce issue.

1. Install your lightbox2.
2. Link at least 1 image. (image_a.png - icon, image_b.png - enlarged)
3. Click on image image_a.png to start LB2 and show image_b.png.
4. Replace image_b.png (with different content) on your host account.
5. Click on image to start LB2 and show image_b.png - enlarged 

In my 4 browsers (IE,Opera,FF,GCh) always get first ver. of image_b.png. Even if I deleted image_b.png.

**Comment by ngonhan2k5** [comment]
Lightbox does nothing with cache. The problem is at browser or your hosting (ex: over proxy), Ctrl-F5 will force browser re-get the images.

**Comment by iadegesso** [comment]
I have the same problem... five years far from the last answer... and I disabled all kind of caches in my nodejs express app.

Any news?

Iade Gesso, PhD in Computer Science

**Comment by lokesh** [comment]
@iadegesso I would try posting your question on https://stackoverflow.com/. This looks to be an issue with your express server set up and not your configuration of Lightbox.
