### ISSUE TITLE
Only showing 1 of 2 images in lightbox, despite it being 12.

### ISSUE THREAD

**Issue by es88** [lokesh/lightbox2#408]
Hello,

I have implemented this lighttbox plugin and when clicking onto an image it states below: 1 of 2 Images.
I can only click through 2 images and not the full set of 12.
Can anyone help with this issue?

Code looks like this:  
<a href="img/event-img/2014/2014--2.jpg" data-lightbox="image-2" data-title="">
     <img src="{{ asset('/img/event-img/2014/thumbs/2014--2.jpg') }}" alt="">
</a>

Thanks a lot.

**Comment by valera-rozuvan** [comment]
@es88 Can you please provide the code as a text snippet? For example use the http://pastebin.com/ service. The image in your issue is no longer available.

**Comment by es88** [comment]
Thanks for getting back. I have now fixed the issue.

**Comment by valera-rozuvan** [comment]
@es88 If your issue is resolved, please close this issue. Thanks! = )
