### ISSUE TITLE
use font-awesome replace some icons

### ISSUE THREAD

**Issue by argb** [lokesh/lightbox2#409]
maybe use font-awesome replacing left right close icons is better,this can load more fast.

**Comment by lokesh** [comment]
It would be nice to use a vector format such as SVGs for the icons but downloading the entire Font Awesome icon set is not worth it for this script..

**Comment by daverogers** [comment]
You couldn't make it an option and assume the user has already loaded the font? Or include a custom icon set with just the FA icons being used via icon font generator?
