### ISSUE TITLE
Social media widget (facebook, twitter, ...) on each image in slideshow

### ISSUE THREAD

**Issue by CodingIsCreation** [lokesh/lightbox2#412]
This is a necessary feature these days so it'd be great if the feature is added in the next version. If i'm able to do it, will definitely provide you with the code.

**Comment by sjmogg** [comment]
Folks,

I have hacked version 2.6 to add pinterest, facebook, google+ and twitter links on our web site at http://www.sanctuaryhillretreat.com/

It wouldn't be hard to add a download link in a similar way.

grab the following files.

http://www.sanctuaryhillretreat.com/css/lightbox.css
http://www.sanctuaryhillretreat.com/js/lightbox-2.6.min.js

have fun.

**Comment by lokesh** [comment]
Closing out old issues.

Thanks @sjmogg for sharing your modification. Works great!

I'm keeping social sharing buttons off the roadmap and out of the core script. The goal of this script from it's beginnings till today is to to provide a better *image viewing experience*. I'll let other talented folks add-on features outside the scope of this goal.
