### ISSUE TITLE
Lightbox close button is not showing up

### ISSUE THREAD

**Issue by lrfowler** [lokesh/lightbox2#414]
why is the Lightbox close button is not showing up?
www.axsisconstruction.com

**Comment by anvarulugov** [comment]
After removing the following lines from lightbox.css buttons showed up normally:
```
body:after {
  content: url(../img/close.png) url(../img/loading.gif) url(../img/prev.png) url(../img/next.png);
  display: none;
}
```

**Comment by lrfowler** [comment]
that didn't work for me...

**Comment by anvarulugov** [comment]
Did you check if the path to images are correct?

**Comment by lrfowler** [comment]
the path is correct..

**Comment by XtremeChocoholic** [comment]
Yup, add an  additional “img” folder for these LB images, unless where you already keep your images is called “img”. TY! :)
