### ISSUE TITLE
Would it be possible to add videos ?

### ISSUE THREAD

**Issue by andfelzapata** [lokesh/lightbox2#417]
It would be nice to get videos inside the gallery.

**Comment by canfiax** [comment]
Agreed - I'd love this feature.

**Comment by rachatfig** [comment]
Yep agreed.

**Comment by valera-rozuvan** [comment]
@andrespipe90 , @canfiax , @rachatfig Do you want to add videos that are natively supported by the browser, or some iframe code from 3rd party services such as YouTube?

**Comment by justinmasuga** [comment]
I would be fine with being able to add iframe videos from YouTUbe.

**Comment by andfelzapata** [comment]
Youtube, Vimeo, etc :)

**Comment by lokesh** [comment]
There are alternative scripts that allow you to show videos and html content. The plan is to keep Lightbox focused on displaying images and continue improving this experience. Thanks.
