### ISSUE TITLE
Can I position the image on the left and the description on the right?

### ISSUE THREAD

**Issue by meghanlundy** [lokesh/lightbox2#418]
I have not found a way to do this nicely. Can someone tell me if they have succsesfully done this yet? I want my image and text to be horizontally floated next to each other, image on the left and description on the right.

**Comment by valera-rozuvan** [comment]
@meghanlundy Where will the arrow buttons *Next* and *Previous* go? What should be the maximum width of the text description be? Should it be overflowed, or truncated? Best to provide a mock up image of what you want to achieve. Maybe use the service http://imagebin.ca/ .

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
