### ISSUE TITLE
Use the lightbox for other purposes... like show a 'div' content

### ISSUE THREAD

**Issue by Press64** [lokesh/lightbox2#421]
I want know if it's possible use this to show content and not only images, like 'section' or 'div' text for example. there's a way to do this?

**Comment by canfiax** [comment]
Could be very useful - i.e. for a Vimeo video

**Comment by lokesh** [comment]
There are alternative scripts that allow you to show videos and html content. The plan is to keep Lightbox focused on displaying images and continue improving this experience. Thanks.
