### ISSUE TITLE
Change Item in lightbox with mouseover

### ISSUE THREAD

**Issue by Caddy24** [lokesh/lightbox2#422]
Hello,

I´m trying to achieve an image change with mouseover in the lightbox. 
My client wants a website for lamps, so if have a thumbnail gallery with a mouseover effect to show the turn on/turn off state. On click the lightbox starts and shows the turn off state image. Is it possible to change the picture with a mouseover event?

Thanks,
Carsten

**Comment by lokesh** [comment]
There are no options built into Lightbox to help you with this feature request. To achieve this effect you could attach a mouseover event handler to the image containing ```div``` and switch the image to another image specified in a custom html attribute such as ```data-image-variant="lamp-on.jpg```.
