### ISSUE TITLE
chaging width of .lightboxOverlay

### ISSUE THREAD

**Issue by hondoFargis** [lokesh/lightbox2#426]
We have a very wide 13000 document and the lightbox Overlay absolute position only works ok for the left images. If scrolled right, the image and its caption do show in the center of the window, but the overlay is always left on the left. The more your scroll to the right, the further behind is the overlay, eventually completely left behind on the left side of the doc.
I tried to adjust absolute position, the width, adding margins to imitate the overlay, but nothing works.
Any input will be highly appreciated.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
