### ISSUE TITLE
Add manual initialize of lightbox

### ISSUE THREAD

**Issue by lexxpavlov** [lokesh/lightbox2#427]
I try to use Lightbox with Owl Carousel, which clones some elements for own purpose. The problem is that these cloned elements are plugged to lightbox while its initialize.
The solution - to initialize lightbox before carousel. But this plugin does not have possibility to initialize programmically.

**Comment by valera-rozuvan** [comment]
@lexxpavlov Do you want to initialize the Lightbox plugin selectively on an element, on a set of elements, or page wide with a single method call?

**Comment by lokesh** [comment]
For anybody who might run across this issue, you can call `lightbox.init()` or `lightbox.enable` yourself.
