### ISSUE TITLE
This version I don’t see bottom margin I used to add links or phrases

### ISSUE THREAD

**Issue by XtremeChocoholic** [lokesh/lightbox2#428]
In this version of lightbox I don’t see the bottom margin I used to add links or phrases at the bottom of the opened image.  Is it something I’m missing? or has that feature been discarded please?  Thank you! :)

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
