### ISSUE TITLE
Is it possible to vertical center a image?

### ISSUE THREAD

**Issue by Stevearzh** [lokesh/lightbox2#435]
Lightbox now can make the image horizontal center, but only 50px top from screen. Is it possible to vertical center a image?

For example, we can use $(window).height(); and $("img").height(); to get the height of browser viewport and the image height, then we can set the top value: top =  ($(window).height() - $("img").height() - containerPadding*2) / 2;

Still a learner, I'm not sure if this is possible.

**Comment by lokesh** [comment]
Closing out old issues.

There is not out of the box solution for vertical centering in the viewport but there are some tweaks you can make that will allow it. If anyone is curious, take a look at the discussion in this issue:
https://github.com/lokesh/lightbox2/issues/172
