### ISSUE TITLE
2 rows 3 columns

### ISSUE THREAD

**Issue by tatermater** [lokesh/lightbox2#436]
Pretty simple layout. Top row works, but when clicking on bottom row, images won't load up. Just get buffering window.

Code example: 
row 1 = a href="images/IMG_2510.jpg" data-lightbox="mud" data-title="My caption"  img src="images/thumb/2510-thumb.jpg" class="img-responsive" alt="Custom Concrete Patio" /a

row 2 = a href="images/IMG_2470.jpg" data-lightbox="mud" data-title="My caption"  img src="images/thumb/IMG_2470-thumb.jpg" class="img-responsive" alt="Concrete Steps" /a

Thoughts?

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.
