### ISSUE TITLE
make only lightbox image to scroll vertically not the html content behind it

### ISSUE THREAD

**Issue by gauravmanral** [lokesh/lightbox2#438]
i have made the lightbox image height to go full height using "this.fitImagesInViewport = false;"

my problem is when scrolling through lighbox the background html content is also scrolled. I want only lightbox image to scroll vertically not the html content behind.

**Comment by skmasq** [comment]
I just stumbled upon this issue, would be nice if it was like in photoswipe

**Comment by lokesh** [comment]
A ```disableScrolling``` option now existing to prevent page scrolling behind the Lightbox once it is open.
https://github.com/lokesh/lightbox2/blob/master/src/js/lightbox.js#L52
