### ISSUE TITLE
Option for Prev/Next button to be in footer of viewer

### ISSUE THREAD

**Issue by kylebellamy** [lokesh/lightbox2#440]
I'd like to be able to move the image buttons into the footer next to the close icon for better grouped navigation. Is this possible currently?

**Comment by valera-rozuvan** [comment]
@kylebellamy I think it would be best if the position of the *Prev* and *Next* buttons could be set via some percentage relative to the height of the image. Would this be helpful? This can be moved to an initialization configuration block.

**Comment by kylebellamy** [comment]
I tried that but it ends up being of the edge of the bottom. I was thinking more of physically moving the buttons to the footer next to the close button.

**Comment by xuragor** [comment]
Did you in your CSS file to a: link formatted with padding or margin ? Take that away or make a pseudo class . (sorry , the text is translated with google)

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Using Github Issues for bugs only now. Thanks.
