### ISSUE TITLE
Working with mass amount of images breaks page heigth

### ISSUE THREAD

**Issue by badsyntaxx** [lokesh/lightbox2#442]
Hello. I love the plugin but when working with hundreds of images it causes firefox to height to stretch.
you can see an example here http://ballpointmachinist.com/volume-one.php

When you scroll to the bottom the page scrolls past the footer. Only happens on firefox not chrome, safari, ie, or opera.

When inspecting with firebug I see a vdh stuff under the body

**Comment by lokesh** [comment]
The link you posted does not work anymore. If this issue still exists, can you repost a link to the issue or all the relevant code below. Once you do that I will reopen. Thanks.

**Comment by badsyntaxx** [comment]
Oops sry. I thought I wasn't gonna get a reply. Anyway the link is working again. However this issue seems to have corrected itself in the latest version of firefox. Display:none; seems to be working to hide the vdh-mask now.
