### ISSUE TITLE
Autoplay images lightbox

### ISSUE THREAD

**Issue by ericcort** [lokesh/lightbox2#443]
How do you autoplay images using lightbox?

**Comment by lokesh** [comment]
Given the following link on the page:

```html
<a class="example-image-link" href="images/demopage/image.jpg" data-lightbox="example-set">Example Link</a>
```

You can automatically start Lightbox once the DOM is loaded by running the following code:
```js

$(function() {
    lightbox.start($('.example-image-link'));
});
```

**Comment by ericcort** [comment]
Didn’t work. I’m using html5 and css3.
http://www.eyepopdesign.com <http://www.eyepopdesign.com/>

On Jun 16, 2015, at 12:26 AM, Lokesh Dhakar <notifications@github.com> wrote:

Given the following link on the page:

<a class="example-image-link" href="images/demopage/image.jpg" data-lightbox="example-set">Example Link</a>
You can automatically start Lightbox once the DOM is loaded by running the following code:

$(function() {
    lightbox.start($('.example-image-link'));
});

**Comment by SomiXD** [comment]
Hi Lokesh  i have a problem the funktion start the light box when i go the first time on my web page but i search for an option to autoplay the galery img 250 pices in autoplay give it an option too do that ?
