### ISSUE TITLE
Prev/Next buttons not showing up

### ISSUE THREAD

**Issue by LisaBee224** [lokesh/lightbox2#444]
All is working fine except the "prev" and "next" buttons  are not showing up. My image paths are correct, and I've tried dropping the "img" folder they are in directly into the css folder. The "close" button does show up, though. Anyone else have this problem??

**Comment by jeannes** [comment]
I have this problem as well.

**Comment by Boris160** [comment]
I have a similar problem:
"prev"-button works well, just "next"-button appears in the images 2, 3, ... of a set not as overlay of the enlarged picture, but in a new line of site after the picture and "close"-button works as "next"-button. See attached picture.

Kind regards

Boris

**Comment by Boris160** [comment]
Sorry: forgot attaching picture :-(
![lightbox](https://cloud.githubusercontent.com/assets/12671955/7897193/91cc1652-06d3-11e5-887d-acdef8b00323.jpg)

**Comment by Boris160** [comment]
I have found a solution for the problem:
1st I changed .lb-nav a.lb-next { width: 60%;
2nd I have edited some pictures, which where very high but not wide, I cutted some not necessary inches at top and bottom
Now next-buttom appears at the correct place
