### ISSUE TITLE
Is there a way to modify the data-title text?

### ISSUE THREAD

**Issue by Kotoriii** [lokesh/lightbox2#446]
Like the title says, I wish to add some sort of customized font/size/color whatever for the title, and add a sub-title/text below it if possible, but since there is absolutely no documentation or customizing options, I have no idea if this is even possible. Any thoughts? Thanks!

**Comment by lokesh** [comment]
Since this issue was reported earlier this year I have stripped much of the custom styling out of lightbox.css. The plugin does a better job of blending into to the existing page by utilizing existing fonts and colors.

To customize further, overwrite the rules in lightbox.css.
