### ISSUE TITLE
Images display in reverse order 

### ISSUE THREAD

**Issue by web385** [lokesh/lightbox2#447]
I'm using the lightbox2 script and am grouping several images together however they are showing up in the reverse order and when the lightbox comes up it starts at the end and you have to keep hitting previous to view all the images.

 <a href="img/image-2.jpg" data-lightbox="roadtrip">Image #2</a>
	<a href="img/image-3.jpg" data-lightbox="roadtrip">Image #3</a>
	<a href="img/image-4.jpg" data-lightbox="roadtrip">Image #4</a>

**Comment by lokesh** [comment]
Were you able to resolve this issue? If not, can you post a link to the issue or the relevant code. Once you do that I will reopen and investigate. Thanks.

**Comment by msikio** [comment]
Hello, I'm getting the same problem, any thoughts ?

http://sqc.diskstation.me/~ssedition/acoustique/Gallery_test_Michel.htm

(Select first image on the top right)

Thanks in advance

**Comment by lokesh** [comment]
@msikio you can fix this by moving the other anchor tags that link to the images in the set below the anchor that is used to open up Lightbox.

<img width="1126" alt="quelque_realisations_acoustiques" src="https://user-images.githubusercontent.com/51469/33232855-2267e43c-d1c2-11e7-8000-13274b309260.png">

I can see why this is counter intuitive though. I will look to get an update in. Thanks.

**Comment by msikio** [comment]
@lokesh Thanks a lot... That's great help
