### ISSUE TITLE
Rotate image?

### ISSUE THREAD

**Issue by gshaxor** [lokesh/lightbox2#450]
How i can rotate an image in fullscreen? 90°

**Comment by lokesh** [comment]
You cannot rotate with Lightbox. This is something you should do with the images ahead of time in a graphics application.

**Comment by gshaxor** [comment]
I do not want to modify the image, rotate only to CSS to view rotated 90°. 
How I can add a button to do it myself? :(

**Comment by lokesh** [comment]
@gshaxor this feature is not on the roadmap for Lightbox.

If you want to do it yourself I would add a another attribute to the image link, maybe ```data-rotate="90"```, that you read with Javascript and use to apply a CSS transform. Goodluck!
