### ISSUE TITLE
IE8 BUG chenge can support IE8  also apper in Chrome

### ISSUE THREAD

**Issue by innerpeacelove** [lokesh/lightbox2#451]
hello Lightbox2 is greet frame , it help a lot
i should use it in IE8 ,but there is a bug 

sound code： 

 preloader.src = this.album[imageNumber].link; 
 this.currentImageIndex = imageNumber;
  
when you debug this sound code：you will find the bug , it also apper in Chrome
if change it like the following code:

 this.currentImageIndex = imageNumber;
 preloader.src = this.album[imageNumber].link;

this bug will be ok! thanks;

**Comment by lokesh** [comment]
@innerpeacelove can you post a link to a page where I can see the problem? Maybe you can create a jsfiddle or codepen example. I am unable to recreate the issue. Thanks.

**Comment by Huberttao** [comment]
thank you！
