### ISSUE TITLE
Increase or decrease space between images in page

### ISSUE THREAD

**Issue by planetjordan** [lokesh/lightbox2#452]
Hello, i have this website->http://www.trigalerie.at/ and i want to decrease the space between images like the image below->
![index php extra](https://cloud.githubusercontent.com/assets/4333386/8089845/0505e5f2-0fb3-11e5-86e4-374eedba12a0.jpg)

**Comment by lokesh** [comment]
@planetjordan can you post a link to the issue or all the relevant code below. Once you do that I will reopen. Thanks.
