### ISSUE TITLE
FitImagesToViewport only working horizontally

### ISSUE THREAD

**Issue by f1roro** [lokesh/lightbox2#455]
When I first loaded lightbox, the images fitted the viewport both horizontally and vertically. I changed the setting FitImagestoViewport from 'true' to 'false' to see how it looked, but now I've changed it back to 'true', images are only being re-sized on the horizontal plane. Vertically, larger images are exceeding the screen height.

I've deleted and re-loaded the code, re-named it to eliminate caching problems, but still have the same issue. Have searched here for likely solutions, but not coming up with anything that helps.

Any ideas? (in language a novice will understand, please!)

Edit to add: working fine in IE, but same issue (as described above) in both Chrome and Firefox.

**Comment by lokesh** [comment]
@f1roro can you post a link to the issue or all the relevant code below. Once you do that I will reopen. Thanks.

**Comment by f1roro** [comment]
Thanks - have narrowed it down to the following in Chrome and Safari (assuming Firefox the same but can't test at work), IE appears fine (except that the Lightbox opens underneath a video iframe further down the page, but that's a separate issue!):

fitImagesToViewport set to 'true' - works as expected when page length is shorter than Viewport (see: http://leemead-timeline.co.uk/files/events/test2.html ), but when page length is longer than ViewPort, the picture displays full-size or limited by width only (see: http://leemead-timeline.co.uk/files/events/test1.html )

**Comment by f1roro** [comment]
Hi – I posted links to the issue a few days ago, hope you’ll be able to take another look. Thanks.

**Comment by f1roro** [comment]
Issue resolved by the added ‘max width’ and ‘max height’ attributes in v.2.7.2.

Thank you.
