### ISSUE TITLE
Show in loop

### ISSUE THREAD

**Issue by idoshhh** [lokesh/lightbox2#457]
Hi, Is there option to continue to click on next image and loop it from the beginning? 
If so, I will be so happy to know how. :) 
Thanks.

**Comment by lokesh** [comment]
@idoshhh in ```lightbox.js```, find the following code which is around line 24:
```
this.wrapAround                  = false;
```

Set this value to ```true```.

**Comment by idoshhh** [comment]
thank you so much sir :)

On Wed, Jun 17, 2015 at 1:34 AM, Lokesh Dhakar <notifications@github.com>
wrote:

> @idoshhh <https://github.com/idoshhh> in lightbox.js, find the following
> code which is around line 24:
>
> this.wrapAround                  = false;
>
> Set this value to true.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lokesh/lightbox2/issues/457#issuecomment-112593518>.
>



-- 
[image: photo]
*Ido Shahar*
Photograper & Web Developer
m:+972-54-643-4444 | w: www.idoshahar.com
 | a: Tel-Aviv
<http://facebook.com/idoshhh>  <http://linkedin.com/in/idoqments>
<http://twitter.com/idoshhh>
 I  recently  uploaded
<http://instagram.com/p/vxr1c_i_Uv/> <http://instagram.com/p/vvJLfyi_Ru/>
<http://instagram.com/p/vq1t1Yi_bd/> <http://instagram.com/p/vgjnLli_b8/>
<http://instagram.com/p/vVy9lnC_bt/> <http://instagram.com/p/u7nKI0C_U0/>

**Comment by mksglu** [comment]
The new version just use `wrapAround:!0`
