### ISSUE TITLE
Bug: Using Base64 Image in IE not working, in Firefox perfect

### ISSUE THREAD

**Issue by Sardoan** [lokesh/lightbox2#458]
I am using asp.net MVC 4/5. My controller is sending a model with a base64 encoded png. 
FF:
![ff](https://cloud.githubusercontent.com/assets/6061781/8262341/19d1defc-16d2-11e5-925e-e3c6581160bf.png)
IE11:
![ie11](https://cloud.githubusercontent.com/assets/6061781/8262345/1f3b3244-16d2-11e5-8cb9-b26b268f5446.png)

The preview looks fine, but after the click on the image in IE 11 I only get the beginning of the image, About 95% is black. In FireFox the image is 100% loaded after clicking the small preview image. 
Any workaround for this? Or is the problem a base64 size limitation of IE?

**Comment by lokesh** [comment]
Reviewing old issues.

My gut says this issue has to do with encoding and is not a Lightbox script problem, but I could definitely be wrong. If anyone is still seeing this issue and can post a link to a test case where I can investigate I will reopen. Thanks!
