### ISSUE TITLE
Reverse images in the lightbox

### ISSUE THREAD

**Issue by Sonnyluu** [lokesh/lightbox2#459]
Hello,

I recently used the lightbox2 and came accros a problem.
I placed a few images in one lightbox and when I open it, it starts with the last image, so I have to click 'previous' to see another picture.

Here is a screenshot from my code. 
http://gyazo.com/2056d57bc475f016ee12592a582ff495

http://i271780.iris.fhict.nl/designtoets/#portfolio2 Here's an example. When you click on the pictures you'll see that the lightbox will open with the last image first.

**Comment by lokesh** [comment]
@Sonnyluu you have one link that you click to trigger the Lightbox. Make sure all the other image ```<a>``` tags are placed below that link in your html.

Here is animated gif (2.4mb download) showing the fix:
http://g.recordit.co/ZulvXHdBmj.gif
