### ISSUE TITLE
Files in Version 2.7.4 are the same as in 2.7.3 / Opacity and round corners wont work

### ISSUE THREAD

**Issue by wartok** [lokesh/lightbox2#460]
Think you made a mistake with the files. the zip file of version 2.7.4 contains all the files of version 2.7.3 Even the jquery Library is still on version 2.x

Additional question ... why does it not work that the black background have an opacity - on my screen its complete black. Also the corners are not round.

Using Win7, IE9

-----------------------------------------
Solved one problem... add the following command in lightbox.css
filter:alpha(opacity=80);
Then it will work with IE9, and maybe other browsers

Solved the problem with the round corners for IE9
in the HTML File add the command
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

**Comment by lokesh** [comment]
Re: rounded corners and opacity on overlay

I was not able to recreate these issues. I tested in IE 11 and IE 9 on Windows 7 using Virtualbox emulation on OSX.

Re: Incorrect version number in zip

My mistake!
