### ISSUE TITLE
"Getting started" section in project website is missing some important details

### ISSUE THREAD

**Issue by ADTC** [lokesh/lightbox2#463]
There are some problems with the instructions given in the [Getting started](http://lokeshdhakar.com/projects/lightbox2/#getting-started) section of the project site.

In trying to use your excellent Lightbox 2 library, I have encountered the same issue as this chap did as he posted in [his SO question](http://stackoverflow.com/q/31147257/1134080). In the same question I have answered how I managed to resolve the issue, which is as follows:

> Lightbox 2 will not work with jQuery 1.x. And the placement of the `<script>` tag matters.

> 1. Use **jQuery 2.x**.
>  - If you don't already use jQuery in your page, simply use `lightbox-plus-jquery.min.js` instead as it includes jQuery 2.1.4.
>  - If you already use it, upgrade to jQuery 2.x and test out your existing jQuery-based code and plugins. *Hopefully nothing else breaks* `=)`
> 1. Put the Lightbox 2 `<script>` tag (for the JavaScript file) **at the end of the page**, just before the body closing tag (`</body>`).
>  - The `<link>` tag for the CSS can remain in the `<head>` tag.

I hope you will consider updating the "Getting started" section to include these important details.

**Comment by lokesh** [comment]
@ADTC thanks for noting this. I'll try to reproduce the issue and update the Getting Start section accordingly.

**Comment by CrateMayne** [comment]
Just wanted to chime in that I recently upgraded from 2.7.1 to 2.8.0, and it still works perfectly fine with jQuery 1.9.0... With, or without, needing to use jQuery Migrate.

Anyways, great work on the lightbox!

**Comment by ADTC** [comment]
It didn't work with jQuery 1.11.3 which I was incidentally using for Bootstrap. Luckily Bootstrap worked fine with jQuery 2, so I was able to upgrade.

**Comment by lokesh** [comment]
@CrateMayne Thanks for testing Lightbox w/jQuery 1.9.

@ADTC I investigated the minimum version jQuery requirement you asked about.

Lightbox 2.8.0 works with jQuery 1.7 and up. jQuery 1.7 introduced the ```.on()``` and ```.off()``` event APIs which are being utilized by Lightbox. http://blog.jquery.com/2011/11/03/jquery-1-7-released/

I'm updating the main site (lokeshdhakar.com/projects/lightbox2/) to note the minimum jQuery requirements as well as adding a tip about loading the scripts at the bottom of the page.

Thanks for the feedback!

**Comment by ADTC** [comment]
Thanks @lokesh nice to see the changes. I must have mixed up the wrong placement of <script> tag with the jQuery version incompatibility. But still, something good came out of it :smile:
