### ISSUE TITLE
open link in new window, lightbox.min.js

### ISSUE THREAD

**Issue by cherylr** [lokesh/lightbox2#466]
I am trying to figure out a way to open a link in the caption to open in a new window. I found this: https://github.com/lokesh/lightbox2/pull/299/files#diff-6cb9fdf664369e4a61b7802ec961c161R330 and changed the code as suggested in lightbox.js; however, my lightbox seems to point to: lightbox.min,js. 

This code in this file appears in one giant paragraph - line #9 includes the majority of the code. I am not sure what I am looking for and what to replace here. 

I am (obviously) not a coder at all but can follow straightforward instructions. Thanks

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
