### ISSUE TITLE
Lightbox2 not on composer

### ISSUE THREAD

**Issue by chewett** [lokesh/lightbox2#467]
I would like to use this with composer (https://getcomposer.org) for my PHP projects but it doesnt have a composer file detailing the package and its details.

Would a PR adding this package file (so that it can be installed with composer install) be accepted?

Many thanks

**Comment by lokesh** [comment]
Closing out old issues.

As far as package management goes, keeping things in sync with NPM and Bower is enough work. 😛

**Comment by chewett** [comment]
Once the composer.json file is added, no further work is needed on your part.
Packagist picks up the new versions from the github tagged releases.
If you would consider it I dont mind making the composer.json file (which is all that is needed).

Thanks for the consideration
Chewett

**Comment by Guite** [comment]
:+1: for composer support
