### ISSUE TITLE
grunt build in win7

### ISSUE THREAD

**Issue by wang191X** [lokesh/lightbox2#475]
C:\wamp\www\lightbox2>grunt build
Running "jscs:src" (jscs) task
Invalid line break at src/js/lightbox.js :
     1 |/*!
-----------^
     2 | * Lightbox v2.8.1
     3 | * by Lokesh Dhakar
>> 1 code style errors found!
Warning: Task "jscs:src" failed. Use --force to continue.
Aborted due to warnings.

**Comment by lokesh** [comment]
There are ways to solve this but since this linter rule isn't important for this project I will simple remove it. Thanks for catching.

The lint rule that was causing issue in 
```
#.jscrc
"validateLineBreaks": "LF"
```
