### ISSUE TITLE
Wrong height with max-height 100%

### ISSUE THREAD

**Issue by mpskovvang** [lokesh/lightbox2#478]
Hi,

Thanks for a great lightbox library!

Just a little heads up. If your stylesheet contains something like this:
```css
img {
    max-height: 100%;
}
```

The lightbox will never use the right image height, as the default 250x250px contianer forces the image height to 250px and afterwards the code uses the image element's height to adjust the container size.

Suggestion: Either the lightbox stylesheet can override the image max-height or the javascript can use the preloader height instead of image element's height - just a quick thought.

**Comment by khuramali123** [comment]
Hi, 
you remove this css img {
    max-height: 100%;
}

**Comment by lokesh** [comment]
Good catch!

I've added a `max-height: none;` to the lightbox image css rule to override any max-height that was set outside the script.
