### ISSUE TITLE
Incorrectly shown under Android browser

### ISSUE THREAD

**Issue by AndreyF75** [lokesh/lightbox2#486]
Lightbox2 version - v2.8.1 - 2015-07-09 shows pictures fine with desktop browsers but does not do it well on Android devices - both with Android browser and Chrome. Substrate is shown as if page were shrinked in some times. How pages looks like before:
![01](https://cloud.githubusercontent.com/assets/15351954/10775582/bbf924a2-7d1a-11e5-8df9-96d5cd061d41.png)

How it looks like when lightbox2 appears:
![02](https://cloud.githubusercontent.com/assets/15351954/10775605/f2d091ae-7d1a-11e5-9b9c-c1e1cb959268.png)

How it looks in default size:
![03](https://cloud.githubusercontent.com/assets/15351954/10775614/0891b6e4-7d1b-11e5-93c0-5336efb1aa8c.png)

If I press picture:
![04](https://cloud.githubusercontent.com/assets/15351954/10775622/2071aae4-7d1b-11e5-8e9f-f26fe7c5a377.png)

And substrate. It is shown ... somewhere in the left side of the page:
![05](https://cloud.githubusercontent.com/assets/15351954/10775634/3e3d86ba-7d1b-11e5-8883-ec88b3b91388.png)

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.

I did not test on a physical Android device in the past so this could have been, and could still be, a real issue.
