### ISSUE TITLE
Lightbox on page inside iframe

### ISSUE THREAD

**Issue by bencagri** [lokesh/lightbox2#488]
Hi there, I'm using lightbox2 on a page called as iframe.
When I click, lightbox appears on top of (iframe) page. How can I set it in middle of iframe page?
If there would be a selector trigger, it would be awesome.

**Comment by spyninja** [comment]
Any luck with this? I think this could be a common issue.

**Comment by bencagri** [comment]
no luck. I could not manage.

**Comment by lokesh** [comment]
Sorry, no out-of-the-box way to do this. But I've added an item in the roadmap for version 3 to consider `allowing placement inside of a specified element`. Feature request noted.
