### ISSUE TITLE
More fadein options

### ISSUE THREAD

**Issue by vegarda** [lokesh/lightbox2#491]
I want image to fade in instantly so i can quickly browse through images.

lightbox.js:316
this.$lightbox.find('.lb-image').fadeIn(this.options.someFadeInDuration);

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
