### ISSUE TITLE
URL links in data-title not working in some instances.

### ISSUE THREAD

**Issue by camilos** [lokesh/lightbox2#492]
Basically, the HREF link in the data-title attribute is not working sometimes. I added a class to the tag  

<  a class='submitCreateFromPreview' href='#'>

 In my Jquery code, there is code that should get triggered when the class is touched. But it doesn't work. It is never triggered. I tried other workaround but nothing works. 

See full details below.

http://stackoverflow.com/questions/34582040/lightbox2-data-title-description-link-with-javascript

**Comment by lokesh** [comment]
Closing out old issues.

Looks like the discussion has moved to StackOverflow. 👍
