### ISSUE TITLE
Missing navi buttons

### ISSUE THREAD

**Issue by maczek83** [lokesh/lightbox2#493]
I'm using Lightbox 2 with my Wordpress page to view photos. From last version update I'm getting strange behavior of the plugin. Navigation keys are missing - I can't navigate to next or previous photo. Problem is more strange, because it occurs only at latest posts on page, and not old ones. It seems that hoverNav is set "display: none" instead of "display:block" in posts where problem occurs. Maybe some suggestions how to solve this problem?

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
