### ISSUE TITLE
Border in the top of the lightbox

### ISSUE THREAD

**Issue by anamariasosam** [lokesh/lightbox2#494]
![screenshot 2016-01-14 20 20 05](https://cloud.githubusercontent.com/assets/2703269/12342832/3d9750c8-bafc-11e5-9ce1-3c0e7cafb178.png)

The class .lightbox has a extra border in the top.

I fixed it, modifying the style:  

`.lightbox {
  padding: 0;
  height: 0 !important;
}`

Maybe it's not the best solution.

**Comment by lokesh** [comment]
Closing out old issues.

I was never able to recreate this issue. 😕 

Thanks for reporting and submitting a PR to resolve the issue you were seeing.
