### ISSUE TITLE
Why is document.load not in there?

### ISSUE THREAD

**Issue by imvunoah** [lokesh/lightbox2#497]
http://stackoverflow.com/questions/34440731/lightbox-2-not-working

**Comment by fmms** [comment]
just wanted to report the same issue. took me a lot of time to find my mistake. Even though it is mentioned in the documentation, this is easily overseen.

Solution at http://stackoverflow.com/questions/34440731/lightbox-2-not-working/34447470#34447470 would solve this for many users, i guess.

**Comment by fmms** [comment]
There is even a pull request https://github.com/lokesh/lightbox2/pull/482 for this issue. I have just tested it and it works fine for me.

**Comment by lokesh** [comment]
This has been fixed recently and will be in the next release v2.9.0 coming out in 2 days:
https://github.com/lokesh/lightbox2/commit/7047214f77cfc8f892e8513426b57d45bf29e9cd
