### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by tiagoboldt** [lokesh/lightbox2#498]
I would very much appreciate if lightbox was able to rotate the image being overlayed. I can image it as being an option such as: 
```
<script>
    lightbox.option({
      'enableRotation': true,
    })
</script>
```
The option would place two buttons, to rotate the image +90º and -90º.
Your thoughts?

EDIT: someone has already tried to do this at http://jsfiddle.net/pootie/EBLc7/

**Comment by Huberttao** [comment]
What browser do you use

**Comment by tiagoboldt** [comment]
Chrome mostly, Firefox and Safari occasionally. But I fail to see the relevance of it.

**Comment by Huberttao** [comment]
You can use **jquery.rotate** and easily solve the rotation problem.Still do not know, I can send you the code.

**Comment by lokesh** [comment]
Looks like the linked jsfiddle does what you're looking for. The example could benefit from using css transforms to smooth out the animations but otherwise it works well!

This feature isn't requested enough to be in the main codebase though so I'm closing out this issue.
