### ISSUE TITLE
Next arrow appearing below image

### ISSUE THREAD

**Issue by cmejlak** [lokesh/lightbox2#499]
Hi I'm developing a wp theme and for some reason on some images the next arrow is appearing below the image - any ideas
![lightbox ss](https://cloud.githubusercontent.com/assets/16001113/12585760/bcc56da8-c44d-11e5-85f2-a37fb3d99503.png)

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
