### ISSUE TITLE
upload more image

### ISSUE THREAD

**Issue by famarinu** [lokesh/lightbox2#501]
Hi @lokesh ,
I inserted the lightbox inside the bxSlider slideshow.
When I go to open the lightbox at the end of a set of images repeat the first two images. I realized when I uploaded 3 images in the label and writes 5 images [http://famarinu.com/page/page.html](url)
How can I fix it?
Thank you!
Manuela

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
