### ISSUE TITLE
Next & Prev Offset

### ISSUE THREAD

**Issue by Web-duck** [lokesh/lightbox2#503]
In the lightbox.css you have at line 106 and 124
  width: 34%;   // Prev
  width: 64%;  // Next
Giving you more hover on the Next link.

This correct this with a dead zone of 30% in the middle
  width: 34%;   // Prev
  width: 34%;  // Next

**Comment by lokesh** [comment]
This was intentional as most of the time you are moving forward. Thanks for the feedback though. Appreciated!
