### ISSUE TITLE
Add Hover Border

### ISSUE THREAD

**Issue by Web-duck** [lokesh/lightbox2#504]
This will give you a hover border when you assign classes to LINK and IMAGE 

your.css
`.lightbox-link {
	display: inline-block;
	margin:2px 0px;
	padding: 4px;
	border-radius: 4px;
	background-color: #fff;
}
.lightbox-link:hover {
  margin:2px 0px;
  padding: 4px;
  background-color:#2B87C6;
}`

your.html
`<a class="lightbox-link" href="your.jpg" ><img class="lightbox-img" src="your-th.jpg"></a>`

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
