### ISSUE TITLE
CSS http://jigsaw.w3.org/css-validator/ compliance?

### ISSUE THREAD

**Issue by mro** [lokesh/lightbox2#505]
I wonder why http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Frawgit.com%2Flokesh%2Flightbox2%2Fmaster%2Fdist%2Fcss%2Flightbox.css&profile=css3 brings 20 errors and if that's considered a bad thing, thx.

**Comment by Magnumv44** [comment]
This hacks for Internet Explorer

**Comment by mro** [comment]
ic, so they seem inevitable, right?
