### ISSUE TITLE
Images starting at last

### ISSUE THREAD

**Issue by gpeth398** [lokesh/lightbox2#509]
I used your tutorial and got ligthbox2 to work on my website. However, it loads my last image first. So when I click on the link it will start at image 4 of 4. I have read other posts with this issue, but am having a hard time making sense of them. I have attached an image of my code, can you help me out?

![capture](https://cloud.githubusercontent.com/assets/17972895/13909725/5eccc840-eee6-11e5-83f7-7dcda6e7be81.PNG)

**Comment by Huberttao** [comment]
What browser do you use

**Comment by gpeth398** [comment]
using google chrome

**Comment by Huberttao** [comment]
Could you describe the problem more specific?

**Comment by gpeth398** [comment]
I am making a portfolio website to show my school projects and I would like to have a main image for each project, that will open a lightbox for all the other images of that project. Right now when I click on the image link it goes straight to image 4 of 4 instead of opening image 1 of 4. All the images are there, but I have to click backwards to see image 3,2, and 1.

**Comment by Huberttao** [comment]
Which version of the lightbox you are using now？
you can try to reverse the two code.
lightbox.js :        381line                 preloader.src= this.album[imageNumber].link;
                          382line                this.currentImageIndex = imageNumber;
Reverse the two code like this:
lightbox.js :        381line                 this.currentImageIndex = imageNumber;
                          382line                preloader.src= this.album[imageNumber].link;

**Comment by gpeth398** [comment]
I am currently using version 2.8.2. I tried reversing the two lines around but there was no change.

**Comment by Huberttao** [comment]
Do you use Bootstrap in your program?

**Comment by gpeth398** [comment]
yes i do

**Comment by Huberttao** [comment]
Your <a> Tag is missing ">"  .
Bootstrap and lightbox are not compatible , I think ...

**Comment by Huberttao** [comment]
Your a Tag is missing ">" .

**Comment by gpeth398** [comment]
Can you be more specific? Which line and where should ">" be?

**Comment by Huberttao** [comment]
![image](https://cloud.githubusercontent.com/assets/17529823/14007393/410a0002-f1b1-11e5-9f4c-c17dde967e18.png)
Inside the picture.

**Comment by Huberttao** [comment]
`a` tag

**Comment by gpeth398** [comment]
i figured it out:) thanks for the help!

**Comment by Huberttao** [comment]
No need to thank！

**Comment by lokesh** [comment]
Closing out old issues.

Good to see the situation resolved. Team work! 👍
