### ISSUE TITLE
Can you add all images as base64 encoded images to CSS? That saves 4 HTTP requests -> Speed!

### ISSUE THREAD

**Issue by cpl-repo** [lokesh/lightbox2#510]
Hi lokesh,

great plugin!
Can you add those images as base64 encoding to CSS, that would save 4 HTTP request which speeds up a lot:
http://cl.ly/3X3V3c383E1m

Cheers,
Chris

**Comment by cdp1337** [comment]
Hey Chris, I actually switched them to FontAwesome in my local fork; as that's already included in this specific project.  You could try that as well by adding the necessary &lt;i&gt; tag and remove the background: url(...)

**Comment by lokesh** [comment]
The concern about reducing excessive HTTP requests has been noted. Though this issue will be less of a concern HTTP/2, it is still a legitimate performance issue now. My plan for v3 of the script is to use inline svgs to solve this issue. Less requests and no additional dependencies.
