### ISSUE TITLE
Contianer width isn't resizing correctly

### ISSUE THREAD

**Issue by jjboathouse** [lokesh/lightbox2#511]
When changing images in the lightbox it will resize to a smaller images porportions. If the next or prev image in the set is a larger image the lightbox container will not resize to that images width and instead the larger image is scaled down to the smaller width. However the height does resize properly. What should be changed so the .lb-outerContainer resizes correctly from smaller to larger widths.

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Thanks.
