### ISSUE TITLE
Lightbox position problem...

### ISSUE THREAD

**Issue by Evrenercan** [lokesh/lightbox2#513]
I am trying to use lightbox on my webpage, but lightbox images are located under the background images. So how can i put the lightbox images on the background images? Thanks a lot in advance.

**Comment by bcarvalho89** [comment]
Try something like that: 
`<div class="bg" style="background-image: url(your_imgl.jpg);">
<a href="your_imgl.jpg" data-lightbox="galery"></a>
</div>`

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
