### ISSUE TITLE
Safari and Mozilla issue

### ISSUE THREAD

**Issue by JuCyy** [lokesh/lightbox2#515]
Hi,

Lightbox works perfectly on Chrome : 
http://www.blog.romain-baly.fr/westin-bonaventure-los-angeles/

But not on Safari and mozilla. I don't understand why if someone can help me :)

Thanks!

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
