### ISSUE TITLE
I wanna use Zepto.js instead of jQuery

### ISSUE THREAD

**Issue by WhiteCat6142** [lokesh/lightbox2#521]
Zepto.js is an alternative to heavy jQuery.However,it doesn't support all jQuery methods,so lightbox2-zepto.js doesn't works.

Here is an error:
`TypeError: this.$outerContainer.outerWidth is not a function`

(just note: animate() is optional)

**Comment by blueForestIcarus** [comment]
You could roll your own functions and add them to zepto as plugins.

This gist should work for you:
https://gist.github.com/wheresrhys/5823198#file-gistfile1-txt

**Comment by lokesh** [comment]
I'm closing this issue but keeping the following PR open:
https://github.com/lokesh/lightbox2/pull/522

For v3 which is still in planning stages I will likely remove all JS deps.
