### ISSUE TITLE
can not show popup when use lightbox

### ISSUE THREAD

**Issue by tentruycapcuaban** [lokesh/lightbox2#526]
Hi all
any help
here my code 
![image](https://cloud.githubusercontent.com/assets/17898925/16402331/ecd7ba3c-3d15-11e6-9dc8-92bf1a5b16b8.png)

<div id="contact-link" >	
	<a onclick="document.getElementById("lightbox10").click();"  href="https://www.youtube.com/embed/I4nYXDpeFVE?autoplay=1" title="video demo">Huong dan su dung</a>              
		<script src="../default-bootstrap/js/jquery-2.1.1.min.js"> </script>
                <script src="../default-bootstrap/js/bootstrap.min.js"> </script>
                <script src="../default-bootstrap/js/bootstrap-media-lightbox.js"> </script>
                <script src="../default-bootstrap/js/run_prettify.js"> </script>
                <script type="text/javascript">
                    jQuery('#lightbox10').lightbox();              
                </script>
================
when i click 'Huong dan su dung' it not show popup-> go to direct link youtube 
wrong here ????

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
