### ISSUE TITLE
Need a way to control the image's "flash" fade duration

### ISSUE THREAD

**Issue by teo1978** [lokesh/lightbox2#532]
You can control the duration of the fade-in and fade-out of the main overlay, container, or whatever it is called.

However, the image itself has a fade-in animation, which by default looks like a kind of "flash" because it fades in on a white background, and there is no option, or at least no documented option, to control the duration of _that_ animation.

**Comment by lokesh** [comment]
Added a `imageFadeDuration` option. Incoming in v2.9.0:
https://github.com/lokesh/lightbox2/commit/6d5f99a65f189a5d2bd7bbfac4682fe36e62871e
