### ISSUE TITLE
The way the border is built is messy

### ISSUE THREAD

**Issue by teo1978** [lokesh/lightbox2#533]
The enlarged image looks like it has a 4px-thick white border.

However, the way this is actually achieved is:
- nothing has any real border
- the outer container has white background and padding
- the outer container has a border radius but has a zero-width border. This creates the rounded corners
- the image has zero-width border too, and it has a border radius less than the container's border radius, because the contour of the rounded corners of the image makes the actual inner contour of the fake border, and hence it has to be a bit less in order not to look weird.

This is a very hacky way to build a border, and makes customizing the style very painful.

**Comment by lokesh** [comment]
I agree with all of the above! It requires multiple css edits to customize a simple border.

The reason for this complication is that when you are navigating a set of images you want to keep this 'border' visible while at the same time fading in and out the images. This is the reason that the images weren't originally given a simple css border.

Here is how it looks now:
![cr5atyw0wb](https://cloud.githubusercontent.com/assets/51469/19713831/3e9d0caa-9afe-11e6-8c04-b3b6706e2812.gif)

Here is what it would look like with the removal of the white background on the outer container and the addition of css borders on the images:
![kyyhmey7jv](https://cloud.githubusercontent.com/assets/51469/19713842/4f68cac4-9afe-11e6-8566-b1a780b39d3e.gif)

With some Javascript magic it would be possible to allow a user to simply set css borders on the images and have the transitions render as they do now. Or even simpler would be to add Javascript options for border controls. I have opted again these approaches for simplicity.

**Comment by teo1978** [comment]
> Here is what it would look like with the removal of the white background on the outer container and the addition of css borders on the images

Sorry but that's kind of a straw man. You just removed the background altogether and put a border, as if that was *the* solution to the issue, and showed it would look bad, hence you conclude that the issue can't be (easily) fixed without the result looking bad.

Assuming you do want the white background (which I find awful, but that's another story), couldn't you just have a background the exact size of the image (rather than a few pixels larger to create a fake border) *and* a proper border??

No need for "Javascript magic", and also the background wouldn't have to be the same color as the border.

> I have opted again[st] these approaches for simplicity.

This is your software and of course you are free to opt for and against whatever you want, but please, please, don't blame "simplicity".

**Comment by lokesh** [comment]
@teo1978 Thanks for all the feedback. Again, you bring up some really good points.

> "...straw man. You just removed the background"
I agree this comparison was done in haste. 

I'm testing some changes that would allow users to set the border directly on the image and would continue to support the previous 'padding to expose parent container bg hack':
https://github.com/lokesh/lightbox2/commit/214361297f1dd5f0c19c1d80ff37c398cdda55cb
