### ISSUE TITLE
Nav on touch devices

### ISSUE THREAD

**Issue by teo1978** [lokesh/lightbox2#534]
For touch devices you currently have two options:
- set `alwaysShowNavOnTouchDevices` to **true**: you *always* see the navigation buttons on top of the image, you can't get rid of them and see the part of the image hidden behind them. **Annoying**.
- set `alwaysShowNavOnTouchDevices` to **false**: you *never* see the navigation button. You can't even know if they are there. You navigate blindly by clicking on the right or left portion of the image without any indication whatsoever that this is supposed to let you navigate in the first place. **Poor UI**.

There should be a third option, which could be the default behavior on touch devices when `alwaysShowNavOnTouchDevices` is false (unless you can think of something even better), that is:
- navigation buttons are not visible at first (or viceversa: this could be a separate option)
- touching anywhere on the image (except on or near the buttons themselves, when visible) would toggle (i.e. show/hide) them

Related: #530.
Note however that while #530 is a feature request, this one is a usability issue.

**Comment by lokesh** [comment]
The Lightbox scripts were originally created in a desktop dominated world where mobile web usage was limited. And the lackluster mobile/touch experience shows that mobile was an after thought.

I'm not planning any more work on the v2.x mobile web experience. Though I understand how this issue qualifies as usability issue if the dev creates a gallery and it is unclear to the user how to navigate between the images on mobile. I'm going to let it stand as is in v2.x.

v3.0, which is in planning, will completely rethink the mobile experience. I'll be exploring gestural navigation for forward/prev navigation, tilt panning for panoramas, and making it clear visually that the image being viewed is part of a set, besides many other things.
