### ISSUE TITLE
Error resizing from landscape to portrait

### ISSUE THREAD

**Issue by jufracaqui** [lokesh/lightbox2#541]
Going from portrait to landscape bugs the resizing of the web on mobile devices but no the other way around. I'm using version 2.8.2. of lightbox on android 4.4.2
![1](https://cloud.githubusercontent.com/assets/15031367/18429290/dce2e1ee-78d2-11e6-9044-db27b96965c8.png)
![2](https://cloud.githubusercontent.com/assets/15031367/18429296/e138d3b6-78d2-11e6-9ca7-4baaf23fc905.png)

**Comment by lokesh** [comment]
Was this issue in Mobile Chrome or the Android Browser?

I'm going to close this issue as I am unable to recreate. But... I will reopen once someone else can recreate and provide details on their platform, browser, and lightbox version. Thanks!

**Comment by jufracaqui** [comment]
Sorry for not beeing able to write before. This issue happend while using cordova and the latest release of lightbox at the time.
