### ISSUE TITLE
Errors in IE7

### ISSUE THREAD

**Issue by snj-shvchnk** [lokesh/lightbox2#542]
Crashed, when try to get **_this.currentImageIndex_** in IE7, it was undefined.

Has no problems after I changed line 31:
**_this.currentImageIndex = void 0;_**
to
**_this.currentImageIndex = 0;_**

What do you think about?

**Comment by lokesh** [comment]
Thanks for reporting the bug, and even more importantly, reporting a fix. For the time being, no new work for support any versions of IE below 9 are happening. The audience for these browsers is too small now.

Thanks again!
