### ISSUE TITLE
how can I show just one image?

### ISSUE THREAD

**Issue by daniel180211** [lokesh/lightbox2#543]
I put the lightbox in foreach, so when I pick the button to see the image it should load just one image, but it shows all the images I have in the same folder when I click on right or left the image. how can I do to show just one image? please help me.

**Comment by lokesh** [comment]
Put each image in their own set:
```
<a href="images/image-2.jpg" data-lightbox="set1">Image #2</a>
<a href="images/image-3.jpg" data-lightbox="set2">Image #3</a>
```

For future help getting Lightbox up and running, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
