### ISSUE TITLE
After loading page for second time overlay appears without content on its own

### ISSUE THREAD

**Issue by jufracaqui** [lokesh/lightbox2#546]
I load the gallery from my web dinamically with ajax on a div, when i load the gallery two times the overlay appears without any content.

**Comment by lokesh** [comment]
Hello -- 

For dynamically added content, you'll need to run `lightbox.init()` after the content has been added.

For future help getting Lightbox up and running, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
