### ISSUE TITLE
Doesnt work for external URLs in <a> tags

### ISSUE THREAD

**Issue by draco123456ftw** [lokesh/lightbox2#549]
it just opens the link. preventDefault() call using jquery doesn't help either it just makes the link stop working completely

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
