### ISSUE TITLE
lightbox2 and bxslider

### ISSUE THREAD

**Issue by John1987vlc** [lokesh/lightbox2#550]
Hi, I'am building a website using bxslider and your lightbox2.
They works fine except I can load the images in the same album, I can't use your next previous because bxslider use `<ul><li><a><img></a></li><li><a><img></a></li>.....</ul> `for change between photos and your lightbox need to be all img in the same `<li> or <div>` how can I fix that and use all the potencial of your lightbox? Can you help me? Thanks a lot.

**Comment by lokesh** [comment]
Hi John,
For help getting Lightbox up and running, please post your question on [Stackoverflow](http://stackoverflow.com/). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is for bugs only. Thanks.
