### ISSUE TITLE
The first number of albumLabel will be wrong in IE 8

### ISSUE THREAD

**Issue by guohao111** [lokesh/lightbox2#555]
The version of jquery is 1.8.x. In IE 8 , when I click the next button, the number of current image will be wrong. It seems that the 'currentImageIndex' will be recalculate from 0 in IE 8, but it will be calculate from 1 in IE 9+ or other browsers, since it has been executed once when the first image is loading.

**Comment by lokesh** [comment]
Thank you for reporting the bug but since IE 8's browser share has continued to shrink and Microsoft itself has discontinued support for the browser I am going to update the Lightbox browser support policy to drop IE 8. Sorry for the inconvenience but this will make maintenance and testing easier.

**Comment by guohao111** [comment]
Thank you very much.

**Comment by guohao111** [comment]
I have found the reason. In the function changeImage. you put the 'this.currentImageIndex = imageNumber;' at last. However, the function 'onload' will set the indexof currentImage before the currentImageIndex being chagned. The execute order is different between ie 8 and other browsers.

After I put the 'this.currentImageIndex = imageNumber;'on the front of the 'var preloader = new Image();', it runs well in ie 8.
