### ISSUE TITLE
Use a icon font to replace the images

### ISSUE THREAD

**Issue by johansmitsnl** [lokesh/lightbox2#556]
Hi,

Love the project and I'm informing (not a bug) if there is a possibility to use a font icon library (like: Font-Awesome) for the icons?
This is for the close, next, prev and loading png's and gifs. This makes integration in for example bootstrap more neatly and it scales also nice on high dpi screens.

If there is no option for this (as I saw in the code) would you consider an pull request that makes this feature configurable so that any font icon can be used?

**Comment by lokesh** [comment]
Closing out old issues.

Feature request is reasonable but not something that will go into this version of the script.
