### ISSUE TITLE
Lightbox2 for Koken

### ISSUE THREAD

**Issue by marcosmontero** [lokesh/lightbox2#560]
Hi,

I'm looking for instructions on replacing Koken's native lightbox with Lightbox2.  Has anybody done this? 

Thanks,
Marcos

**Comment by lokesh** [comment]
Closing out old issues.

If you still need help, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2). See more details here: http://lokeshdhakar.com/projects/lightbox2/#help
