### ISSUE TITLE
CSS Issue with lightbox 2

### ISSUE THREAD

**Issue by brandonpowell** [lokesh/lightbox2#562]
When you click on images the lightbox image appears to the bottom of the page?

**Comment by mktmaster** [comment]
I have the same issue!

**Comment by simon1tan** [comment]
I had this problem too until I realized I didn't include the stylesheet properly.

**Comment by lokesh** [comment]
Closing out old issues. 

If anyone is still having the issue, please post a link to where the issue can be reviewed or relevant code. Thanks!
