### ISSUE TITLE
[Feature Request] Support for action toolbar

### ISSUE THREAD

**Issue by sangupta** [lokesh/lightbox2#563]
Add support to load an action toolbar along the image. Say, binding a DOM element to the footer. This will allow us to use lightbox for letting a user run actions on images with a single handler interface.

For example, add the following to options:

```javascript
lightbox.option({
  toolbar: '.lightbox.toolbar'
})
```

And there is a `DIV` somewhere in the body that produces a toolbar:

```html
<div class=".lightbox.toolbar">
    <a href="#" class="button" data-handler="saveImage">Save</a>
    <a href="#" class="button" data-handler="tweetImage">Tweet</a>
</div>
```

where the handlers themselves can be added this way:

```javascript
function saveImage(url, element) {
  // do something
}

function tweetImage(url, element) {
  // do something
}
```

**Note:** Am not a front-end guy, so there may be a better way to structure the code than above.

**Comment by lokesh** [comment]
Closing out old issues.

This feature unfortunately never made it on the [roadmap](https://github.com/lokesh/lightbox2/blob/master/ROADMAP.md).
