### ISSUE TITLE
Hide/unhide select ?

### ISSUE THREAD

**Issue by standus** [lokesh/lightbox2#566]
Hi,

why is this code for select?
```
$('select, object, embed').css({ 
      visibility: 'hidden'
    });
```
Its not needed for select! Why its there?

**Comment by lokesh** [comment]
In older browsers `selects` would be visible through and the overlay div that is placed on top of the page to give it a dim appearance. This doesn't seem to be the case in modern browsers but I haven't had a chance to fully test across the board so I'll be leaving this check in for the time being.
