### ISSUE TITLE
How to add 'alt' (or 'title') attribute with dynamic value for each picture (<img>)

### ISSUE THREAD

**Issue by richandhandsomeman** [lokesh/lightbox2#571]
I have image gallery with pictures loading dynamically. I need 'alt' or 'title' attribute to be showed for each picture

**Comment by lokesh** [comment]
Feature coming in next release. Currently in `dev` branch:
https://github.com/lokesh/lightbox2/pull/609

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0
