### ISSUE TITLE
image duplicated

### ISSUE THREAD

**Issue by jayvicks86** [lokesh/lightbox2#572]
Hi guys, I've now been racking my brains for a couple of hours with no joy any help is appreciated. I click an image in my gallery, lightbox takes effect, however, each image is being duplicated, and I can't find where in the code it is happening? Fairly sure it's somewhere in the js but I can't find where? Anyone had this problem and know how to sort it, please?

**Comment by bgardineer4** [comment]
I have the same problem. No luck yet.

**Comment by bgardineer4** [comment]
Okay, for me it looks like Lightbox was conflicting with Unslider, a jQuery slider plugin I'm using. Disallowing infinite sliders solved the issue. After scouring some other forums, it looks like a few others have had this problem with various slider plugins. I imagine it has something to do with how linking is handled for the edge photos of infinite sliders. I actually wasn't seeing duplicates of my interior images, just the exterior ones (e.g. if I had three photos in my infinite slider and tried displaying them in a Lightbox gallery, images 1 and 3 were duplicated, but image 2 was not).

**Comment by lokesh** [comment]
Closing out old issues. Hopefully everyone made progress on their issue.

**Comment by schiavo** [comment]
Same issue occurs when using lightbox with bxslider. Setting `infiniteLoop: false` fixes the issue.
