### ISSUE TITLE
Jquery Issue

### ISSUE THREAD

**Issue by Blackglade** [lokesh/lightbox2#573]
Currently testing the module. Doesn't seem to work with JQuery Slim 3.1

**Comment by bellhop** [comment]
The slim version is missing the effects modules that are called by lightbox2.  Therefore, if you use the non-slim version it will work.  I have tested on JQuery v3.1.1 from the JQuery CDN.  See below: 
```
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
```

**Comment by Blackglade** [comment]
ahh okay, woops!
