### ISSUE TITLE
Performance issues in IE

### ISSUE THREAD

**Issue by bogdanbikics** [lokesh/lightbox2#575]
Hi,

with my colleagues we found an issue with lightbox.
In IE 11 (maybe also lower) it has some weird performance problems: if you click on a picture once to lightbox it, Explorer will be busy with painting in an infinitive loop (even if you leave the given page), causing quite some CPU usage. On the picture you can see the UI responsiveness chart where I don't do anything just looking at the page.

![lightboxissue](https://cloud.githubusercontent.com/assets/9092394/23369655/5ddac708-fd12-11e6-99a6-2fc8ce57b522.png)

After some investigation I found a solution. If I remove this line from lightbox.css:

```
body:after {
  content: url(../images/close.png) url(../images/loading.gif) url(../images/prev.png) url(../images/next.png);
  display: none;
}
```

then it won't have any problems anymore. I am not sure why it is difficult for IE, my guess is that it just can't handle it and tries it over and over again.
We changed it locally in our own project, but we wanted to inform you too. (maybe later we might also want to use it from npm/bower :) )

Thank you in advance and best wishes!

**Comment by lokesh** [comment]
Old issue. But I want to say, **thank you** for investigating.

I have removed the offending code in a recent PR. The code was originally used as a hack for preloading images via CSS. This isn't necessary any more as the images are loaded once the _lightbox_ markup is appended to the DOM which is on _dom ready_.

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0
