### ISSUE TITLE
Lightbox2 issue with Foundation 6

### ISSUE THREAD

**Issue by LionelRieder** [lokesh/lightbox2#578]
Hello,

I'm trying to use Lightbox2 with a Zurb Foundation 6 project and after add the CSS and JS files I get this error on all pages : 

Uncaught TypeError: Cannot read property 'jQuery' of undefined
    at lightbox.js:25
    at lightbox.js:14

My jQuery version is the 2.2.4 and the lightbox.js is concat at the bottom of app.js

**Comment by gordonchanhk** [comment]
Same issue encountered. I am also debugging just now and spot root for root.jQuery is undefined
https://github.com/lokesh/lightbox2/blob/master/src/js/lightbox.js#L27

And wonder `this` should be `window`?  https://github.com/lokesh/lightbox2/blob/master/src/js/lightbox.js#L29

**Comment by gordonchanhk** [comment]
I find that I have a Gulp script to run Babel with es2015 and turn out the script changing the this in https://github.com/lokesh/lightbox2/blob/master/src/js/lightbox.js#L29 to undefined. Would this be the syntax issue?

**Comment by so-rose** [comment]
Same issue encountered here. Anybody found a fix by any chance?

**Comment by mugukamil** [comment]
@so-rose for fixing, we need to add option to .babelrc `{ "modules": false }`.

Because babel 5 when transpiling *.js files, replace all `this` with `undefined`

**Comment by so-rose** [comment]
@mugukamil Thanks for the fix!

**Comment by lokesh** [comment]
Glad this issue was sorted out. Closing. Thanks to everyone who helped. 👏

**Comment by sthGit** [comment]
Hi!

I'm currently doing an introductory course on JS and added lightbox to project and encountered the same issue, but here instead https://github.com/lokesh/lightbox2/blob/dev/dist/js/lightbox-plus-jquery.js#L10626. Replacing "this" with "typeof this !== "undefined"? this:window, function ($)" at https://github.com/lokesh/lightbox2/blob/dev/dist/js/lightbox-plus-jquery.js#L10628 fixed the issue. However, I wonder if my problem could be solved the same way or if it is a separate issue? I'm using VS code as IDE v. 1.46.1 and Node.js version 12.8.1

**Comment by uzeehan** [comment]
Hi there, I am having the same issue. 
I applied the solution mentioned above to change Babelrc option, but it didn't work for me.
Babelrc option 'modules:false' stopped GridderJs on the site. 

Is there any other solution out there?
