### ISSUE TITLE
Responsive Lightbox image Resizing

### ISSUE THREAD

**Issue by reifnotreef** [lokesh/lightbox2#581]
Hey everyone,

Working on a project for TeamTreehouse right now. I'm using Lightbox2 to create a responsive/dynamic gallery. It's super simple for the most part.

I can't get the Lightbox images themselves to scale. Even using media queries and selecting things very specifically I can't manage to resize them responsively. I checked the docs and there's an option, defaults to true, to resize images so people don't have to scroll to see the entire image. This option does not scale the image on window resize though.

Anyone know a fix for this?
[Here's my repo](https://github.com/reifnotreef/Interactive-Photo-Gallery) if you want to take a look.

**Comment by sakonn** [comment]
Hello, 
Have you sorted out the issue?

**Comment by reifnotreef** [comment]
I'm not sure what I did to fix the issue but it has been resolved.
