### ISSUE TITLE
Jquery 3.x

### ISSUE THREAD

**Issue by hurrycaner** [lokesh/lightbox2#582]
Does lightbox2 works with jquery 3?
If positive, is it possible to update bower dependencies to >2 instead of ~2?

**Comment by pschfr** [comment]
Yup! Check this [CodePen](https://codepen.io/pschfr/pen/oWpXEX?editors=1111)!

**Comment by bgeree** [comment]
Nope! Try the following option:
'albumLabel': false

You'll get this error in console:
`this.options.albumLabel.replace is not a function`

**Comment by lokesh** [comment]
Work w/jQuery 2>. I have a pending change to update the bower.json jquery dep requirements:
https://github.com/lokesh/lightbox2/pull/614

re: `this.options.albumLabel.replace is not a function`
The `albumLabel` prop must be a `String` and not a `Boolean`.

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0
