### ISSUE TITLE
uBlock Origin blocks script execution

### ISSUE THREAD

**Issue by timschmele** [lokesh/lightbox2#585]
Unfortunately I was unable to reproduce this bug. Nevertheless, I want to report this here, so that there is awareness on this issue:

I switched from using the 'rel' attribute to the 'data-lightbox' attribute in my a-tags after updating to the newest version. At first this broke my lightbox functionality: the large image was shown, but the navigation-div and everything around it (title, image number and being able to exit from lightbox) was not being loaded. Looking at the console, I noticed uBlock was aborting script execution.

Disabling uBlock and re-enabling it fixed the problem and I cannot reproduce it now :(

Like I said, sorry to not be of much more help. Keep this report in the archives and hopefully it was just an unlucky glitch.
Cheers!

**Comment by lokesh** [comment]
I haven't heard any other reports of this issue in the past year. So closing it out.

Thanks for reporting.
