### ISSUE TITLE
Image Groups

### ISSUE THREAD

**Issue by Bert-de-Jong** [lokesh/lightbox2#590]
I'm trying to prevent images from grouping together.
So, instead of "Image 2 of 8", I just want all images separately.

I'm using
`<a href="..." data-lightbox="image-49169" rel="lightbox[image-49169]"><img src="..." alt="..."></a>`
where **49169** is replaced by different image IDs.

As you can read above, I'm using both the old rel= and the new data-lightbox=.
Just to be safe, since the Lightbox version I'm using is fairly old.
Unfortunately, it still groups images together.
Any thoughts?

**Comment by lokesh** [comment]
Closing out old issues.

If issue is still relevant, please make a note and I will reopen and investigate. Thanks.

Can you post a link to the issue or the relevant code below. Once you do that I will reopen and investigate. Thanks.
