### ISSUE TITLE
Invalid meta in bower.json

### ISSUE THREAD

**Issue by cjwd** [lokesh/lightbox2#592]
Lightbox install but I have a build process that relies on correctly formed main attribute in the bower.json and you have invalid meta. See screenshot

https://www.dropbox.com/s/tk6rrh71fnvi6sb/Screenshot%202017-08-03%2017.21.46.png?dl=0

**Comment by lokesh** [comment]
Fix queued up in `dev` branch. This will go out shortly. Sorry about that! 

PR: https://github.com/lokesh/lightbox2/pull/613

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0
