### ISSUE TITLE
Ugly flickering on opening and closing an image

### ISSUE THREAD

**Issue by swbdev** [lokesh/lightbox2#596]
When I open or close an image, a strange flickering appears below the image. I seems like this behaviour only appears on Google Chrome (I am using v. 61.0.3163.79 - 64-Bit).

This problem also appears on the demo on http://lokeshdhakar.com/projects/lightbox2/. In this case, I only have this problem on my vertical monitor, so the height of the html document could play a role (or maybe the width/height ratio).

Recorded a video, so you can see what it looks like: [flickering.zip](https://github.com/lokesh/lightbox2/files/1292493/flickering.zip)

**Comment by simon1tan** [comment]
Try modifying the options to reduce the delay http://lokeshdhakar.com/projects/lightbox2/#options

**Comment by masiorama** [comment]
I have the same problem @swbdev  has.
I Tried to reduce duration options but the problem, even if it lasts less time (obviously), still persists.

**Comment by swbdev** [comment]
@masiorama can you update your chrome to the new v62? Actually I can't reproduce that bug anymore.

**Comment by masiorama** [comment]
@swbdev  indeed it disappeared! Thanks.
