### ISSUE TITLE
可以在点开图片的时候添加旋转按钮吗

### ISSUE THREAD

**Issue by BacardiLee** [lokesh/lightbox2#597]

**Comment by simon1tan** [comment]
Yes, I agree this is a great project.

**Comment by lokesh** [comment]
> 可以在点开图片的时候添加旋转按钮吗
>> "Can I add a spin button while opening a picture?" 
From Google Translate.

A spinner does exist now so this issue is unclear. Closing. Happy to re-open if more details are provided.
