### ISSUE TITLE
Strange background error

### ISSUE THREAD

**Issue by carinp2** [lokesh/lightbox2#602]
I have used Lightbox previously and never had the problem I now have. I am not sure if it is my browser version or conflicting js files.

When I open and scroll through images, I get a strange background display. 

Please have a look here:
https://www.graffitibooks.co.za/en/0/BookLaunches/1

Click on Past events and open the 1st image.

![image](https://user-images.githubusercontent.com/33094990/32003901-d7a2be42-b9a0-11e7-854c-9da58c0ebb44.png)

**Comment by DarioCorno** [comment]
Got the same glitch. Did you find a way to solve it?

**Comment by carinp2** [comment]
No fix yet.

**Comment by mehta-ankit** [comment]
@carinp2 was this on chrome 61 windows 10 ? I have seen a similar issue.

**Comment by carinp2** [comment]
Yes, Chrome Version 61 on Win10 and I have no fix yet!

**Comment by lokesh** [comment]
@carinp2 are you still seeing this issue?
