### ISSUE TITLE
All Tag HTML allowed For  Lightbox

### ISSUE THREAD

**Issue by evengyl** [lokesh/lightbox2#603]
according to the css all the HTML tags are concerned by the icon next prev close, ect ...
this line is counterintuitive and takes a lot of resources for nothing

Before.... it's really very heavy

```
body:after {
  content: url(../images/close.png) url(../images/loading.gif) url(../images/prev.png) url(../images/next.png);
  display: none;

}
```

But now, it's very light :)

```
#lightbox{
    :after
    {
        content: url(../images/lightbox/close.png)
        url(../images/lightbox/loading.gif)
        url(../images/lightbox/prev.png)
        url(../images/lightbox/next.png);
        display: none;
    }
}
```

**Comment by lokesh** [comment]
Your proposal is much better than the current code. But after some testing, I noticed that preloading the images via CSS is altogether unnecessary. On _DOM Ready_ the _lightbox_ elements are appended to the `body`. Even though they are hidden with `display: none`, the images are loaded.
