### ISSUE TITLE
When click on second data-lightbox display images form first data-lightbox

### ISSUE THREAD

**Issue by cubiczx** [lokesh/lightbox2#604]
When click on second data-lightbox display images form first data-lightbox with different name, but if i change the name of second data-lightbox in Chrome inspector inline only open image of second data-lightbox.

`see <a href="table1.jpg" data-lightbox="images">Table1</a> see <a href="fig1.jpg" data-lightbox="answer">Figure1</a> `

**Comment by lokesh** [comment]
Can you post a link to where I can see the issue? or can you post more of your code?

I haven't seen this issue before and need more info to recreate and debug. I'll reopen this issue once more context is provided.
