### ISSUE TITLE
disableScrolling doesn't work on mobile

### ISSUE THREAD

**Issue by Maculotti** [lokesh/lightbox2#608]
Hello there,
I set the option disablescrolling as a true but on a mobile device I can still scroll. Why?
this is my code:
```
// Lightbox
  // --------------------------------------------------
  lightbox.option({
    'resizeDuration': 200,
    'alwaysShowNavOnTouchDevices': true,
    'disableScrolling': true,
    'wrapAround': true,
    'fixedNavigation': true,
    'albumLabel' : '%1 / %2'
  })
```

I guess it's due to the hight of #lightboxOverlay element and the value applied to #lighbox element.

**Comment by davemin** [comment]
Same issue

**Comment by lokesh** [comment]
Fix incoming in next release. Currently in `dev` branch. Thanks for reporting.
https://github.com/lokesh/lightbox2/pull/611

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0

**Comment by Maculotti** [comment]
I can't see the image anymore because the image container it's pushed down and the container is fixed.
@davemin is it working in your case?

Thanks

**Comment by Maculotti** [comment]
May I suggest that if the options disableScrolling it's true always position the lightbox like this:
`top: 50%`
`transform: translateY(-50%);`

instead of using top: window.scrollTop() so it will be in the center of the fixed container. 

Thanks
