### ISSUE TITLE
lazysizes + lightbox?

### ISSUE THREAD

**Issue by majkimajki** [lokesh/lightbox2#617]
Hi,

Any idea what might be causing lightbox not to work with lazyzies (https://github.com/aFarkas/lazysizes)?

All images that are lazyloaded do not work in the gallery?

**Comment by lokesh** [comment]
Hi @majkimajki ,

This is a perfect question for [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2).

Github Issues is for lightbox specifc bugs only. Thanks.
