### ISSUE TITLE
Firefox displaying fine line(s) over images after first image in sequence

### ISSUE THREAD

**Issue by WebSpectrum** [lokesh/lightbox2#624]
🐛 **Github issues is for bugs only.** No feature requests or support tickets please.

## Trouble using Lightbox?

1. Search [Stackoverflow](https://stackoverflow.com/questions/tagged/lightbox2) to see if other people have run into similar issues.
3. If you don't find anything similar, then post a new question on [Stackoverflow](https://stackoverflow.com/questions/ask). Use the `lightbox2` tag.

## Have a Feature Request?

1. [Search through existing Github Issues and PRs](https://github.com/lokesh/lightbox2/issues) to see if the feature has been discussed or already created.
2. If not, search [Stackoverflow](https://stackoverflow.com/questions/tagged/lightbox2) to see if other people have made similar requests.
3. If your feature request is unique, then post a new question on [Stackoverflow](https://stackoverflow.com/questions/ask). Use the `lightbox2` tag.

View the project [Roadmap](https://github.com/lokesh/lightbox2/blob/master/ROADMAP.md).

## Found a Bug?

[Search through existing Github Issues](https://github.com/lokesh/lightbox2/issues) that have been reported to avoid creating a duplicate issue. If your bug has not been reported, create a new issue with the following details:

**What version of Lightbox2 you are using?**

**Which browsers and operating systems have you seen the issue on?**

**What are the steps to reproduce the bug?**

**Do you have link to a live site where the bug is visible? or can you post relevant HTML, CSS, and Javascript?**

**Comment by WebSpectrum** [comment]
Further investigation : the display problem in firefox is when hovering over next arrow in a sequence of images,

**Comment by lokesh** [comment]
Closing out old issues.

I was unable to recreate. I tested in Firefox 66 on Mac.
