### ISSUE TITLE
Prevent Lightbox2 activating when thumbnail is dragged

### ISSUE THREAD

**Issue by cursor2000** [lokesh/lightbox2#631]
I'm using Lightbox2 in conjunction with Slider-Pro. When using the mouse to scrub through my image gallery, if a user drags an image to the left or right, Lightbox activates because of the mouse event on the image. Is there a way of preventing Lightbox activating when an image is dragged so it only activates when the mouse is stationary when clicked?

**Comment by lokesh** [comment]
Reviewing older issues.

🤔I was not able to recreate this issue. As seen on the Lightbox page, clicking and dragging a thumbnail does not open up Lightbox. https://lokeshdhakar.com/projects/lightbox2/
