### ISSUE TITLE
Navigation Buttons Not Working

### ISSUE THREAD

**Issue by judia** [lokesh/lightbox2#633]
I can't seem to get the lightbox navigation buttons to show up. everything else works fine, but you can't navigate from image to image.

**Comment by WildCrasher** [comment]
I have the same problem on slimbox2. Sometimes previous button doesn't show up. I discovered, that div of next button overlays div of prev button. I will try to fix it locally in my project, but i send tip for you.

**Comment by lokesh** [comment]
Closing old issues.

Hope everything worked itself out. If there are other issues implementing, please post on Stackoverflow.
