### ISSUE TITLE
position problem when mmenu and lightbox both are configured

### ISSUE THREAD

**Issue by Raemy92** [lokesh/lightbox2#644]
Hi
I have a strange issue when both, lightbox and mmenu are configured: it seems that lightbox adds the divs inside the mmenu overlay container which results in wrong positioning of the lightbox when clicked on a image. the lightbox is always under the footer.

CMS: WordPress 5.1
JQuery: latest (should be 3.3)
URL: http://dev19.planungskonzepte.ch/innenarchitektur/
Screenshot: https://imgur.com/a/6DVgq5z

I tested it with the DOM manipulator in Chrome: When I move the divs outside the mmenu div container, then everything works fine.

Thanks and best regards

**Comment by Raemy92** [comment]
Solved it by adding a new div after the closing </body> tag and changed the append in the lightbox.js script to
`$('<div id="lightboxOverlay" class="lightboxOverlay"></div><div id="lightbox" class="lightbox"><div class="lb-outerContainer"><div class="lb-container"><img class="lb-image" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" /><div class="lb-nav"><a class="lb-prev" href="" ></a><a class="lb-next" href="" ></a></div><div class="lb-loader"><a class="lb-cancel"></a></div></div></div><div class="lb-dataContainer"><div class="lb-data"><div class="lb-details"><span class="lb-caption"></span><span class="lb-number"></span></div><div class="lb-closeContainer"><a class="lb-close"></a></div></div></div></div>').appendTo($('#id-of-the-div'));
`

**Comment by lokesh** [comment]
Glad you were able to sort it out! 👏
