### ISSUE TITLE
Where all documentions about lightbox2's config?

### ISSUE THREAD

**Issue by kanitw** [lokesh/lightbox2#65]
I remember you used to have a lot of docs for config...

**Comment by RyanZim** [comment]
http://lokeshdhakar.com/projects/lightbox2/#options

**Comment by lokesh** [comment]
There used to be a small FAQ and a forum as well. But both of those were difficult to maintain so I have offloaded everything to [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2).

With the exception of a [Getting Started section](http://lokeshdhakar.com/projects/lightbox2/#getting-started) and an [Options table](http://lokeshdhakar.com/projects/lightbox2/#options).
