### ISSUE TITLE
overflow hidden on body not working

### ISSUE THREAD

**Issue by sorenwagemans** [lokesh/lightbox2#656]
## overflow hidden on body not working

I downloaded your latest version of lightbox 2, but it seems that when I use it, it's still possible to scroll on the body of the page when the lightbox is opened. I saw that this error was also in your demo examples. => https://lokeshdhakar.com/projects/lightbox2/#examples

When I look in the code, I see that the body is not affected after opening the lightbox.
![afbeelding](https://user-images.githubusercontent.com/23070639/56979508-46d42080-6b7a-11e9-8917-1172d5ccdcb1.png)

Any possible fixes for this problem?

**Comment by lokesh** [comment]
@sorenwagemans did you turn on the `disableScrolling` option? By default it is set to `false`.
https://lokeshdhakar.com/projects/lightbox2/#options

**Comment by sorenwagemans** [comment]
Ow yea, I see, did it change over the years? Because I can't remember having to change it when I first used it. Sorry for the trouble and thank you for the solution.

**Comment by lokesh** [comment]
np! I'm going to close. I think this was reopened on accident. But if there is any other issues let me know.
