### ISSUE TITLE
lightbox should support these functionality

### ISSUE THREAD

**Issue by M-hanif** [lokesh/lightbox2#665]
lightbox uses some images for left next , right next and a spinner if you want to use these images it should be in same directory as your gallery images are fading. the issue is right here. 
suppose my images are fading from a remote server with an ajax call  then its not efficient to load lightbox required images on ajax calls.  
so please add a supportable configuration that user could specify the directory route of lightbox required images. 
thanks

**Comment by lokesh** [comment]
There is not way to read a user's filesystem from the Javascript.
