### ISSUE TITLE
Image disapears and border is cut off

### ISSUE THREAD

**Issue by ecumene** [lokesh/lightbox2#666]
![image](https://i.imgur.com/E3aHseN.png)

**What version of Lightbox2 you are using?**

2.10.0

**Which browsers and operating systems have you seen the issue on?**

Chrome, this bug is reliably found on windows but it's likely there's also issues on other OSs

**What are the steps to reproduce the bug?**

Simply load an image, for whatever reason the border is cutoff and the image isn't there.

**Do you have link to a live site where the bug is visible? or can you post relevant HTML, CSS, and Javascript?**

Unfortunately no, this is for a production app so I can't supply an example past that we're simply using hrefs for the image, and those aren't 404ing.

This is most likely a shot in the dark but perhaps this is a known issue? Thank you for your continued development of this great library!

**Comment by lokesh** [comment]
@ecumene I'm happy to look into this if you can either point me to a URL where this problem exists or if you can post all the relevant code. Unfortunately it is impossible to debug w/o this info as I'm unable to recreate the problem. You should also update to the latest version v2.11.1 just in case.
https://github.com/lokesh/lightbox2/releases
