### ISSUE TITLE
Translation of bottom text in french

### ISSUE THREAD

**Issue by xillibit** [lokesh/lightbox2#670]
I'am wondering how to translate in french the text in bottom of image of the lightbox :+1: 
![traduction_franaise](https://user-images.githubusercontent.com/876395/65760578-90229f00-e11d-11e9-9d64-cfe508c12af3.png)

How to translate this text ?

**Comment by AppDeveloperVM** [comment]
Hey there,
if you look inside ' lightbox.js ' file, in line 43,or in the Lightbox default settings, there is a line where you can have a custom message por the pagination : 

```
Lightbox.defaults = {
...
albumLabel: 'Image %1 of %2',
..
}
```

The text the % symbol followed by numbers are the actual page, and the total of pages.
The text 'Image' can be changed.

**Comment by lokesh** [comment]
Closing out old issues.

Controlling the label is available as an option and doesn't require modifying the source code: https://lokeshdhakar.com/projects/lightbox2/#options

```
<script>
    lightbox.option({
      'albumLabel': 'Image %1 de %2'
    })
</script>
```
