### ISSUE TITLE
CORB issue

### ISSUE THREAD

**Issue by MichalNemec** [lokesh/lightbox2#677]
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.youtube.com/embed/a8fHgx9mE5U with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**What version of Lightbox2 you are using?**
Lightbox v2.11.1

**Which browsers and operating systems have you seen the issue on?**
win10 + wamp apache

**What are the steps to reproduce the bug?**
include this
`<a class="pull-left" href="http://www.youtube.com/embed/a8fHgx9mE5U" data-title="Image 2" data-lightbox="image-set1"><img class="thumbnail" src="http://www.youtube.com/embed/a8fHgx9mE5U" alt=""></a>`

**Comment by lokesh** [comment]
Lightbox works for images only and does not support code embeds or video. 📹
