### ISSUE TITLE
How to turn off Lightbox 2?

### ISSUE THREAD

**Issue by sweetngx** [lokesh/lightbox2#679]
How can I close lightbox 2 when another element is clicked? I am trying to turn off lightbox2 by listening to my keyboard from a different cubicle.

`$("#lightboxOverlay").on("keydown", function (e) {			
// Enter code here.			
});`

**Comment by cf-git** [comment]
```js
Lightbox.end()
```

**Comment by cf-git** [comment]
```js
lightbox.end()
```
