### ISSUE TITLE
SVGs not scaled to max possible size in Chrome

### ISSUE THREAD

**Issue by davidc** [lokesh/lightbox2#681]
SVGs, being scalable, should be displayed at the maximum possible size in the lightbox.

Using Firefox this works as expected. In Chrome, the SVG in the lightbox is tiny, tinier even than the viewbox specified in the SVG.

Lightbox2 version 2.11.1
Problem occurs in Chrome latest but not Firefox latest.
Windows 10

Example SVG:
[overview.zip](https://github.com/lokesh/lightbox2/files/4740725/overview.zip)

Relevant HTML:

    <div>
        <a href="{% link img/network/overview.svg %}" data-lightbox="network" data-title="LONAP Network Overview" style="cursor: zoom-in">
            <img src="{% link img/network/overview.svg %}" alt="LONAP Network Overview" width="845" height="270"/>
        </a>
    </div>

Here is how the lightbox looks in Chrome:

![image](https://user-images.githubusercontent.com/1050152/83950942-9a5d7700-a82e-11ea-9e9f-8d4e7ac9837a.png)

Here is how it looks (correctly) in Firefox:

![image](https://user-images.githubusercontent.com/1050152/83950955-b06b3780-a82e-11ea-8ba5-bfbd4fadb7c7.png)

May be related to #552 however I have upgraded beyond the version fixed in that issue.

**Comment by davidc** [comment]
Edge 44.18362.449.0 is also broken:

![image](https://user-images.githubusercontent.com/1050152/83950998-fe803b00-a82e-11ea-9d73-93d14aac6db6.png)

but Internet Explorer 11 is fine:

![image](https://user-images.githubusercontent.com/1050152/83951049-4010e600-a82f-11ea-9082-a8a5e5ccce70.png)

**Comment by davidc** [comment]
The page demonstrating the issue is now live - top image
https://www.lonap.net/network

**Comment by lokesh** [comment]
Fixed in https://github.com/lokesh/lightbox2/releases/tag/v2.11.2
