### ISSUE TITLE
Escape key not closing lightbox when there is another escape key trigger underneath.

### ISSUE THREAD

**Issue by panicbus** [lokesh/lightbox2#683]
The escape key does not close the lightbox when there is another escape key trigger underneath.

stopPropagation is not preventing event bubbling from capturing the event only in the Lightbox modal.

**Comment by lokesh** [comment]
For help getting Lightbox setup, please post your question on [Stackoverflow](http://stackoverflow.com/questions/tagged/lightbox2) and provide more context about your scenario and paste the relevant code. See more details here: http://lokeshdhakar.com/projects/lightbox2/#help

Github Issues is used for bugs only. Thanks.
