### ISSUE TITLE
Wrong tag for v2.11.2

### ISSUE THREAD

**Issue by janpecha** [lokesh/lightbox2#686]
Hello, I think version `v2.11.2` is tagged on wrong commit, files in `dist` folder are same as in `v2.11.1`.

**Comment by lokesh** [comment]
Thank you for letting me know. Checking on it.

**Comment by lokesh** [comment]
I had accidentally made the release of the `dev` branch and not `master`. I've preserved the v2.11.2 release and updated the description to note that it is equivalent to v2.11.1. A new release has been v2.11.3 that includes the bug fix that was intended for v2.11.1 originally.

Thanks again.

https://github.com/lokesh/lightbox2/releases
