### ISSUE TITLE
Conflict with jquery-bootgrid

### ISSUE THREAD

**Issue by HajaTahiriniaina** [lokesh/lightbox2#687]
I try to use the library **jquery-bootgrid** with the lightbox2. The jquery-bootgrid is loaded before the lightbox and when I try to use call the function _$().bootgrid()_ , the console tell me that _$.bootgrid is not a function_ 
With other jquery extension, bootgrid works but when I load lightbox2, it throws an exception.

**Comment by lokesh** [comment]
_Closing out old issues._

For specific implementation issues, please post on Stackoverflow. [Getting script support](https://lokeshdhakar.com/projects/lightbox2/#help)
