### ISSUE TITLE
Images not expanding in Microsoft Edge browser any more?

### ISSUE THREAD

**Issue by NJWebDesign** [lokesh/lightbox2#701]
Has something changed in Microsoft Edge browser?  Images are no longer expanding in Microsoft Edge, yet they were doing so previously.  Only appears to be affecting Edge.  Any ideas?

Can be replicated by clicking the "Gallery" link on this page and selecting any of the left/right scrollable images:
https://www.gallowaycottageholidays.com/index.php

Any advice would be greatly appreciated, thank you.
NJ

**Comment by erthi16** [comment]
Strange... I get a violation error in my Chrome version 88 console when I test your gallery.

jquery-latest.pack.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

The lightbox only works outside your slider...

**Comment by NJWebDesign** [comment]
...only on Edge browser.  It works inside the slider in every other browser.  :S

jquery-latest.pack.js is a DMXzone file associated with their Google Maps extension for Dreamweaver so maybe that's causing the problem?

I wouldn't know how to mark an event handler as 'passive'.  :S

**Comment by NJWebDesign** [comment]
Haven't found any solution to this yet.  How do I mark an event handler as "passive" and, even if I did fix that, why wouldn't that be causing a problem in other browsers.  Thank you.

**Comment by lokesh** [comment]
_Closing older issues._

I didn't receive additional reports about Edge issues so I'm assuming this was an issue with the specific implementation (e.g. conflict with another script on the page).

**Comment by NJWebDesign** [comment]
This is still an issue in Edge browser.  Lightbox2, as I have it set up, works in every browser apart from Edge.

**Comment by NJWebDesign** [comment]
Lokesh, the issue remains with Edge browser.  Lightbox doesn’t work in that browser.

Regards
Nathon Jones
Manager

Telephone:  01671 404 924
Skype:  skype:nathonjones
E-mail:  ***@***.***
Website:  https://www.nathonjones.com<https://www.nathonjones.com/>

***@***.***

Responsive Website Design • Content Management • eCommerce • Domain Name Registration • Dedicated Business E-mail • Website Hosting • Technical Support • Graphic & Logo Design

Nathon Jones Website Design | The Vault Arts Centre | 40 Victoria Street | Newton Stewart | Wigtownshire | Dumfries & Galloway | Scotland | DG8 6BT

This e-mail communication, together with any attachments that may be transmitted with it, is intended only for the use of the addressee and may contain information which is privileged and confidential. If you are not the intended recipient you are hereby notified that any use of this e-mail is strictly prohibited. If you have received this e-mail in error please immediately delete it and any copies of it. Any opinions expressed in this e-mail are those of the author and do not necessarily constitute the views of Nathon Jones Web Design. Nothing in this e-mail shall bind Nathon Jones Web Design in any contract or obligation.
