### ISSUE TITLE
Position image landscape mode / random selection of photo ti display Lightbox

### ISSUE THREAD

**Issue by Sukafkiana** [lokesh/lightbox2#703]
Hi am new doing web pages and I have a problem with the Lightbox. I am using "Lightbox v2.11.3" and the horizontal photo is on the top of the screen in mobiles devices. I read the same problem but doesn't work the solution.

Another problem es the selection of the photos for show in the Lightbox, I am using Colcate horizontal grid, but the Lightbox show me the photos follow the vertical order, I don't know how I can fix it.

![Screen Shot 2021-02-24 at 12 13 05 pm]
(https://user-images.githubusercontent.com/73562012/108930646-68c95c00-769a-11eb-9c71-ec83b816f2da.png)

**Comment by lokesh** [comment]
_Closing out old issues_

It is jumpy on mobile after scroll and that issue is being looked into.
