### ISSUE TITLE
Horizontal white space of lightbox-container with SVG images

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [lokesh/lightbox2#706]
Latest 2.11.3
Chrome, Firefox

Hi there,

using SVG Images results in a lightbox-container with lots of white space left and right. Am I missing something or is it a bug? PNGs and JPGs work as espected -> lightbox-container has the same size like the image.

SVG is 400 x 400 px and the html-tag is like:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Ebene_1" x="0px" y="0px" viewBox="0 0 400 400" style="enable-background:new 0 0 400 400;" xml:space="preserve">`

See screenshot:

[
![lightbox_bug](https://user-images.githubusercontent.com/51790093/109794324-0a5e2980-7c16-11eb-9894-1a06e725f8ce.png)
](url)

**Comment by lokesh** [comment]
Resolved in v2.11.4: https://github.com/lokesh/lightbox2/releases/tag/v2.11.4
