### ISSUE TITLE
Is it possible to add text underneath the small preview pictures?

### ISSUE THREAD

**Issue by rosatheagraham** [lokesh/lightbox2#717]
Hello, nothing worked to add a text under the small pictures. 
It is either placed next to the small picture, or when I try with a new line with different methods, then it doesn't allow small pictures to appear next to each other on the page. All elements start in a new line instead. 

```
<a href="{{asset($elements->file)}}" data-lightbox="mygallery" data-title="{{$elements->title}}">
<img src="{{asset($elements->file)}}">
</a>     
```

I have tried many combinations of:

```
<pre></pre>
style="white-space: pre-line">
style="white-space: pre-wrap">
style="white-space: no-wrap">

```
here and there.

I would be glad, if you have any solution for such feature?

**Comment by lokesh** [comment]
_Cleaning up old issues_

This looks to be an HTML layout question and not related to the script. If anyone still has this issue, I recommend reading up on HTML layouts (flexbox, CSS grid, etc.).
