### ISSUE TITLE
Missing Input Sanitization for Image Titles

### ISSUE THREAD

**Issue by l4rm4nd** [lokesh/lightbox2#724]
**What version of Lightbox2 you are using?**
2.11.3 (latest)

**Which browsers and operating systems have you seen the issue on?**
- Google Chrome
- Microsoft Edge

**What are the steps to reproduce the bug?**
If lightbox2 is used and image data-titles contain unsafe characters such as JS or HTML code, the code will later be executed in the browser if the image is overlayed on the page. Problem is a lack of sanitization when the title is embedded into the "lb-caption" class HTML span object. This might be introduced by file upload functions when the file name is set as title and not properly sanitized.

![image](https://user-images.githubusercontent.com/21357789/189854828-33426a40-d02c-4ec8-ab37-f2a6a4a07d68.png)

The issue was identified in a project that uses lightbox2 for image overlaying. Please see https://github.com/drakkan/sftpgo/issues/981#issuecomment-1244116517 for more information.

**Do you have link to a live site where the bug is visible? or can you post relevant HTML, CSS, and Javascript?**
https://codesandbox.io/s/lightbox2-demo-forked-vh88tp

**Comment by lokesh** [comment]
_Cleaning up old issues_

Keeping sanitization out of scope of the Lightbox script as it can be handled in earlier stages of a project pipeline.
