### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input lightbox-plus-jquery.js:9980

### ISSUE THREAD

**Issue by MSzajowka** [lokesh/lightbox2#725]
Hi,
I spotted that lightbox will simply not work, when using lightbox-plus-jquery.js file. The console gives the error:
Uncaught SyntaxError: Unexpected end of input lightbox-plus-jquery.js:9980
When used lightbox-plus-jquery.min.js then all is fine.

**What version of Lightbox2 you are using?**
> I am using v2.11.3.

**Which browsers and operating systems have you seen the issue on?**
> Chrome Version 105.0.5195.102 (Official Build) (64-bit)
> Windows 10 Enterprise

**What are the steps to reproduce the bug?**
> Just use lightbox-plus-jquery.js and check the console in Chrome.

**Do you have link to a live site where the bug is visible? or can you post relevant HTML, CSS, and Javascript?**
> No.

**Comment by lokesh** [comment]
Cleaning up older issues.

I did not see additional reports about this and was never able to recreate. Closing, but happy to reopen if others can recreate.
