### ISSUE TITLE
Right side of images covered up

### ISSUE THREAD

**Issue by tomtinker** [lokesh/lightbox2#727]
I'm using Lightbox on Moodle 3. When opening images with the gallery open, the right half of images is covered up with a solid pink color. If I mouseover the pink area, the whole image becomes visible. When the mouse pointer is moved outside the right half of the image, the pink cover returns, and only the left half of the image is visible. Is this a known bug?

**Comment by tomtinker** [comment]
p.s. Viewing using Firefox 67 on Windows 10, but this happens on Edge as well.

**Comment by lokesh** [comment]
For specific usage issues, I recommend posting to [Stackoverflow](https://stackoverflow.com/questions/tagged/lightbox2) where the community can assist. I don't have any personal experience with Moodle 3 unforunately.
