### ISSUE TITLE
Lightbox <A> tag crawler

### ISSUE THREAD

**Issue by xKZL** [lokesh/lightbox2#728]
Lightbox (last version) is using <a> tags without href (or empty href). 
Can you replace it by buttons ?

**Comment by lokesh** [comment]
Included in the package is an `index.html` file with examples. I posted one below. The `href` attributes reference the image to be shown.

If you can point me to the place where you saw the issue, I'd be happy to reopen. 

```
  <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-1.jpg" data-lightbox="example-1"><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-1.jpg" alt="image-1" /></a>
```
