### ISSUE TITLE
Request for non jQuery version

### ISSUE THREAD

**Issue by nom3d** [lokesh/lightbox2#729]
Thank you for developing such a great and usable lightbox plugin. I'd to ask about a version that does not require jQuery. Now in 2023 jQuery is less needed than ever and on some projects lightbox would be the only plugin requiring jQuery. Thank you.

**Comment by lokesh** [comment]
@nom3d The request makes sense as jQuery's popularity has dropped, but Lightbox2 is now in maintenance mode and will not be getting any new features or major refactors, only bug fixes. I have a list of ideas on how I would construct a new major version (v3), but that doesn't have a release timeline.
