### ISSUE TITLE
Overlay adds to bottom of page

### ISSUE THREAD

**Issue by TrickyUtrici** [lokesh/lightbox2#734]
Lightbox does not overlay the page, instead it enlarges the page and adds the image at the bottom, way below the normal page end, how do I resolve. I tried installing the latest version of Lightbox but has not resolved. Inspecting the page in the browser shows lightboxOverlay height 7681px which is or course the extra length of the page.

**Comment by TrickyUtrici** [comment]
I resolved it by changing the css link to: <link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen"> the type is probably not needed but as it is it works fine.

**Comment by Aliexperes** [comment]
i had same issue and solution was same. thanks
