### ISSUE TITLE
CSS syntax error ("*zoom")

### ISSUE THREAD

**Issue by drakanor** [lokesh/lightbox2#738]
**What version of Lightbox2 you are using?*

2.11.4

In dist/css/lightbox.css there are two identical typos:

`*zoom: 1;`

line 44 and 142

Found it because Vite/PostCSS was complaing about it while minifying CSS:

```
▲ [WARNING] Unexpected "zoom" [css-syntax-error]

    <stdin>:5315:3:
      5315 │   *zoom: 1;
```

**Comment by OGFaisalN** [comment]
Yep, it messes the rest up:

![image](https://github.com/lokesh/lightbox2/assets/84286255/7bb8626d-485a-47bb-91f8-9f9710c0cf81)

**Comment by ruimendes11** [comment]
Any workaround for this issue?
