### ISSUE TITLE
The "data-lightbox" attribute on the project web page.

### ISSUE THREAD

**Issue by MarelisAdlatus** [lokesh/lightbox2#749]
The page
[https://lokeshdhakar.com/projects/lightbox2/#getting-started](https://lokeshdhakar.com/projects/lightbox2/#getting-started)
says to use the "**data-lightbox**" attribute for the image set, it doesn't work that way for me, but when I look in the source code of the page, it is used there "**data-gallery**" attribute that works.

**Comment by lokesh** [comment]
Closed. Unable to recreate
