### ISSUE TITLE
Adding a youtube link to lightbox

### ISSUE THREAD

**Issue by John1000** [lokesh/lightbox2#80]
I want to use lightbox to open and play a video, anybody know how to do this?
Thanks
John

**Comment by louismagie** [comment]
That would be an awesome feature ...

**Comment by mgmoonlight** [comment]
Still not an option? Looking to display and play an mp4.

**Comment by jaekqubp** [comment]
I was in a position in which I needed to put a video in lightbox, I ended up accomplishing this by nesting another plugin inside the lightbox. If your project is not dependent on lightbox, I would suggest that it may be easier for you to use an alternative code that supports embedded video.

**Comment by justinmasuga** [comment]
Can you explain your nesting inside of lightbox further?
